<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Is it a good practice to use try-except-else in Python? | StackOverflow Snapshot</title>
<link href="../../assets/css/all-nocdn.css" rel="stylesheet" type="text/css">
<meta name="theme-color" content="#5670d4">
<meta name="generator" content="Nikola (getnikola.com)">
<link rel="canonical" href="https://ohstackoverflow.netlify.app/posts/is-it-a-good-practice-to-use-try-except-else-in-python/">
<!--[if lt IE 9]><script src="../../assets/js/html5.js"></script><![endif]--><meta name="author" content="Arya">
<link rel="prev" href="../mongod-complains-that-there-is-no-data-db-folder/" title="Mongod complains that there is no /data/db folder" type="text/html">
<link rel="next" href="../how-do-i-find-the-time-difference-between-two-datetime-objects-in-python/" title="How do I find the time difference between two datetime objects in python?" type="text/html">
<meta property="og:site_name" content="StackOverflow Snapshot">
<meta property="og:title" content="Is it a good practice to use try-except-else in Python?">
<meta property="og:url" content="https://ohstackoverflow.netlify.app/posts/is-it-a-good-practice-to-use-try-except-else-in-python/">
<meta property="og:description" content="From time to time in Python, I see the block:
try:
   try_this(whatever)
except SomeException as exception:
   #Handle exception
else:
   return something


What is the reason for the try-except-else ">
<meta property="og:type" content="article">
<meta property="article:published_time" content="2023-02-18T05:26:59+08:00">
<meta property="article:tag" content="exception">
<meta property="article:tag" content="python">
<meta property="article:tag" content="try-catch">
</head>
<body>
<a href="#content" class="sr-only sr-only-focusable">Skip to main content</a>

<!-- Menubar -->

<nav class="navbar navbar-inverse navbar-static-top"><div class="container">
<!-- This keeps the margins nice -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar" aria-controls="bs-navbar" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="https://ohstackoverflow.netlify.app/">

                <span id="blog-title">StackOverflow Snapshot</span>
            </a>
        </div>
<!-- /.navbar-header -->
        <div class="collapse navbar-collapse" id="bs-navbar" aria-expanded="false">
            <ul class="nav navbar-nav">
<li>
<a href="../../archive.html">Archive</a>
                </li>
<li>
<a href="../../categories/">Tags</a>

                
            </li>
</ul>
<ul class="nav navbar-nav navbar-right">
<div style="display:table;min-height:5rem;min-width:27rem;">
					<div class="input-group" style="display: table-cell;vertical-align: middle;">
						<input id="words" type="text" class="form-control" style="max-width:22rem;" onkeydown="if(event.keyCode==13){btn.click()}"><span class="input-group-btn" style="float:left">
							<button id="btn" class="btn btn-default" type="button" data-toggle="modal" data-target="#myModal">
								<span class="glyphicon glyphicon-search">
							</span></button>
						</span>
					</div>
<!-- /input-group -->
				</div>

				
                
                
                
            </ul>
</div>
<!-- /.navbar-collapse -->
    </div>
<!-- /.container -->
</nav><!-- End of Menubar --><!-- 模态框（Modal） --><div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×
				</button>
				<h4 class="modal-title" id="myModalLabel">
					查找结果
				</h4>
			</div>
			<div class="modal-body">
				<div id="search-count" style="min-height:4rem;">
				查找中，请稍后...
				</div>
				<div id="search-result">
				</div>

				
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">
					关闭
				</button>
			</div>
		</div>
<!-- /.modal-content -->
	</div>
<!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="container" id="content" role="main">
    <div class="body-content">
        <!--Body content-->
        <div class="row">
            
            
<article class="post-text h-entry hentry postpage" itemscope="itemscope" itemtype="http://schema.org/Article"><header><h1 class="p-name entry-title" itemprop="headline name"><a href="." class="u-url">Is it a good practice to use try-except-else in Python?</a></h1>

        <div class="metadata">
            <p class="byline author vcard p-author h-card"><span class="byline-name fn p-name" itemprop="author">
                    <a class="u-url" href="../../authors/arya/">Arya</a>
            </span></p>
            <p class="dateline">
            <a href="." rel="bookmark">
            <time class="published dt-published" datetime="2023-02-18T05:26:59+08:00" itemprop="datePublished" title="2023-02-18 05:26">2023-02-18 05:26</time></a>
            </p>
            

        </div>
        

    </header><div class="e-content entry-content" itemprop="articleBody text">
    <p>From time to time in Python, I see the block:</p>
<div class="code"><pre class="code literal-block"><span class="k">try</span><span class="o">:</span>
<span class="w">   </span><span class="n">try_this</span><span class="o">(</span><span class="n">whatever</span><span class="o">)</span>
<span class="n">except</span><span class="w"> </span><span class="n">SomeException</span><span class="w"> </span><span class="k">as</span><span class="w"> </span><span class="n">exception</span><span class="o">:</span>
<span class="w">   </span><span class="err">#</span><span class="n">Handle</span><span class="w"> </span><span class="n">exception</span>
<span class="k">else</span><span class="o">:</span>
<span class="w">   </span><span class="k">return</span><span class="w"> </span><span class="n">something</span>
</pre></div>

<p><strong>What is the reason for the try-except-else to exist?</strong></p>
<p>I do not like that kind of programming, as it is using exceptions to perform
flow control. However, if it is included in the language, there must be a good
reason for it, isn't it?</p>
<p><strong>It is my understanding that exceptions are not errors</strong> , and that they
should only be used for exceptional conditions (e.g. I try to write a file
into disk and there is no more space, or maybe I do not have permission), and
not for flow control.</p>
<p>Normally I handle exceptions as:</p>
<div class="code"><pre class="code literal-block"><span class="nv">something</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="nv">some_default_value</span>
<span class="nv">try</span>:
<span class="w">    </span><span class="nv">something</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="nv">try_this</span><span class="ss">(</span><span class="nv">whatever</span><span class="ss">)</span>
<span class="nv">except</span><span class="w"> </span><span class="nv">SomeException</span><span class="w"> </span><span class="nv">as</span><span class="w"> </span><span class="nv">exception</span>:
<span class="w">    </span>#<span class="nv">Handle</span><span class="w"> </span><span class="nv">exception</span>
<span class="nv">finally</span>:
<span class="w">    </span><span class="k">return</span><span class="w"> </span><span class="nv">something</span>
</pre></div>

<p>Or if I really do not want to return anything if an exception happens, then:</p>
<div class="code"><pre class="code literal-block"><span class="k">try</span><span class="o">:</span>
<span class="w">    </span><span class="n">something</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="n">try_this</span><span class="o">(</span><span class="n">whatever</span><span class="o">)</span>
<span class="w">    </span><span class="k">return</span><span class="w"> </span><span class="n">something</span>
<span class="n">except</span><span class="w"> </span><span class="n">SomeException</span><span class="w"> </span><span class="k">as</span><span class="w"> </span><span class="n">exception</span><span class="o">:</span>
<span class="w">    </span><span class="err">#</span><span class="n">Handle</span><span class="w"> </span><span class="n">exception</span>
</pre></div>

<p><br><br></p>
<h2>Answer</h2>
<blockquote>
<p>"I do not know if it is out of ignorance, but I do not like that kind of
programming, as it is using exceptions to perform flow control."</p>
</blockquote>
<p>In the Python world, using exceptions for flow control is common and normal.</p>
<p>Even the Python core developers use exceptions for flow-control and that style
is heavily baked into the language (i.e. the iterator protocol uses
<em>StopIteration</em> to signal loop termination).</p>
<p>In addition, the try-except-style is used to prevent the race-conditions
inherent in some of the "look-before-you-leap" constructs. For example,
testing <em>os.path.exists</em> results in information that may be out-of-date by the
time you use it. Likewise, <em>Queue.full</em> returns information that may be stale.
The try-except-else style will produce more reliable code in these cases.</p>
<blockquote>
<p>"It my understanding that exceptions are not errors, they should only be
used for exceptional conditions"</p>
</blockquote>
<p>In some other languages, that rule reflects their cultural norms as reflected
in their libraries. The "rule" is also based in-part on performance
considerations for those languages.</p>
<p>The Python cultural norm is somewhat different. In many cases, you <em>must</em> use
exceptions for control-flow. Also, the use of exceptions in Python does not
slow the surrounding code and calling code as it does in some compiled
languages (i.e. CPython already implements code for exception checking at
every step, regardless of whether you actually use exceptions or not).</p>
<p>In other words, your understanding that "exceptions are for the exceptional"
is a rule that makes sense in some other languages, but not for Python.</p>
<blockquote>
<p>"However, if it is included in the language itself, there must be a good
reason for it, isn't it?"</p>
</blockquote>
<p>Besides helping to avoid race-conditions, exceptions are also very useful for
pulling error-handling outside loops. This is a necessary optimization in
interpreted languages which do not tend to have automatic loop invariant code
motion.</p>
<p>Also, exceptions can simplify code quite a bit in common situations where the
ability to handle an issue is far removed from where the issue arose. For
example, it is common to have top level user-interface code calling code for
business logic which in turn calls low-level routines. Situations arising in
the low-level routines (such as duplicate records for unique keys in database
accesses) can only be handled in top-level code (such as asking the user for a
new key that doesn't conflict with existing keys). The use of exceptions for
this kind of control-flow allows the mid-level routines to completely ignore
the issue and be nicely decoupled from that aspect of flow-control.</p>
<p>There is a nice blog post on the indispensibility of exceptions here.</p>
<p>Also, see this Stack Overflow answer: Are exceptions really for exceptional
errors?</p>
<blockquote>
<p>"What is the reason for the try-except-else to exist?"</p>
</blockquote>
<p>The else-clause itself is interesting. It runs when there is no exception but
before the finally-clause. That is its primary purpose.</p>
<p>Without the else-clause, the only option to run additional code before
finalization would be the clumsy practice of adding the code to the try-
clause. That is clumsy because it risks raising exceptions in code that wasn't
intended to be protected by the try-block.</p>
<p>The use-case of running additional unprotected code prior to finalization
doesn't arise very often. So, don't expect to see many examples in published
code. It is somewhat rare.</p>
<p>Another use-case for the else-clause is to perform actions that must occur
when no exception occurs and that do not occur when exceptions are handled.
For example:</p>
<div class="code"><pre class="code literal-block"><span class="nv">recip</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="nv">float</span><span class="ss">(</span><span class="s1">'Inf'</span><span class="ss">)</span>
<span class="nv">try</span>:
<span class="w">    </span><span class="nv">recip</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="mi">1</span><span class="w"> </span><span class="o">/</span><span class="w"> </span><span class="nv">f</span><span class="ss">(</span><span class="nv">x</span><span class="ss">)</span>
<span class="nv">except</span><span class="w"> </span><span class="nv">ZeroDivisionError</span>:
<span class="w">    </span><span class="nv">logging</span>.<span class="nv">info</span><span class="ss">(</span><span class="s1">'Infinite result'</span><span class="ss">)</span>
<span class="k">else</span>:
<span class="w">    </span><span class="nv">logging</span>.<span class="nv">info</span><span class="ss">(</span><span class="s1">'Finite result'</span><span class="ss">)</span>
</pre></div>

<p>Another example occurs in unittest runners:</p>
<div class="code"><pre class="code literal-block"><span class="k">try</span><span class="o">:</span>
<span class="w">    </span><span class="n">tests_run</span><span class="w"> </span><span class="o">+=</span><span class="w"> </span><span class="mi">1</span>
<span class="w">    </span><span class="n">run_testcase</span><span class="o">(</span><span class="k">case</span><span class="o">)</span>
<span class="n">except</span><span class="w"> </span><span class="n">Exception</span><span class="o">:</span>
<span class="w">    </span><span class="n">tests_failed</span><span class="w"> </span><span class="o">+=</span><span class="w"> </span><span class="mi">1</span>
<span class="w">    </span><span class="n">logging</span><span class="o">.</span><span class="na">exception</span><span class="o">(</span><span class="s1">'Failing test case: %r'</span><span class="o">,</span><span class="w"> </span><span class="k">case</span><span class="o">)</span>
<span class="w">    </span><span class="n">print</span><span class="o">(</span><span class="s1">'F'</span><span class="o">,</span><span class="w"> </span><span class="n">end</span><span class="o">=</span><span class="s1">''</span><span class="o">)</span>
<span class="k">else</span><span class="o">:</span>
<span class="w">    </span><span class="n">logging</span><span class="o">.</span><span class="na">info</span><span class="o">(</span><span class="s1">'Successful test case: %r'</span><span class="o">,</span><span class="w"> </span><span class="k">case</span><span class="o">)</span>
<span class="w">    </span><span class="n">print</span><span class="o">(</span><span class="s1">'.'</span><span class="o">,</span><span class="w"> </span><span class="n">end</span><span class="o">=</span><span class="s1">''</span><span class="o">)</span>
</pre></div>

<p>Lastly, the most common use of an else-clause in a try-block is for a bit of
beautification (aligning the exceptional outcomes and non-exceptional outcomes
at the same level of indentation). This use is always optional and isn't
strictly necessary.</p>
<p><br></p>
<h3>Suggest</h3>
<blockquote>
<h3>What is the reason for the try-except-else to exist?</h3>
</blockquote>
<p>A <code>try</code> block allows you to handle an expected error. The <code>except</code> block
should only catch exceptions you are prepared to handle. If you handle an
unexpected error, your code may do the wrong thing and hide bugs.</p>
<p>An <code>else</code> clause will execute if there were no errors, and by not executing
that code in the <code>try</code> block, you avoid catching an unexpected error. Again,
catching an unexpected error can hide bugs.</p>
<h4>Example</h4>
<p>For example:</p>
<div class="code"><pre class="code literal-block"><span class="k">try</span><span class="o">:</span>
<span class="w">    </span><span class="n">try_this</span><span class="o">(</span><span class="n">whatever</span><span class="o">)</span>
<span class="n">except</span><span class="w"> </span><span class="n">SomeException</span><span class="w"> </span><span class="k">as</span><span class="w"> </span><span class="n">the_exception</span><span class="o">:</span>
<span class="w">    </span><span class="n">handle</span><span class="o">(</span><span class="n">the_exception</span><span class="o">)</span>
<span class="k">else</span><span class="o">:</span>
<span class="w">    </span><span class="k">return</span><span class="w"> </span><span class="n">something</span>
</pre></div>

<p>The "try, except" suite has two optional clauses, <code>else</code> and <code>finally</code>. So
it's actually <code>try-except-else-finally</code>.</p>
<p><code>else</code> will evaluate only if there is no exception from the <code>try</code> block. It
allows us to simplify the more complicated code below:</p>
<div class="code"><pre class="code literal-block"><span class="nv">no_error</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="nv">None</span>
<span class="nv">try</span>:
<span class="w">    </span><span class="nv">try_this</span><span class="ss">(</span><span class="nv">whatever</span><span class="ss">)</span>
<span class="w">    </span><span class="nv">no_error</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="nv">True</span>
<span class="nv">except</span><span class="w"> </span><span class="nv">SomeException</span><span class="w"> </span><span class="nv">as</span><span class="w"> </span><span class="nv">the_exception</span>:
<span class="w">    </span><span class="nv">handle</span><span class="ss">(</span><span class="nv">the_exception</span><span class="ss">)</span>
<span class="k">if</span><span class="w"> </span><span class="nv">no_error</span>:
<span class="w">    </span><span class="k">return</span><span class="w"> </span><span class="nv">something</span>
</pre></div>

<p>so if we compare an <code>else</code> to the alternative (which might create bugs) we see
that it reduces the lines of code and we can have a more readable,
maintainable, and less buggy code-base.</p>
<h4><code>finally</code></h4>
<p><code>finally</code> will execute no matter what, even if another line is being evaluated
with a return statement.</p>
<h3>Broken down with pseudo-code</h3>
<p>It might help to break this down, in the smallest possible form that
demonstrates all features, with comments. Assume this syntactically correct
(but not runnable unless the names are defined) pseudo-code is in a function.</p>
<p>For example:</p>
<div class="code"><pre class="code literal-block"><span class="k">try</span><span class="o">:</span>
<span class="w">    </span><span class="n">try_this</span><span class="o">(</span><span class="n">whatever</span><span class="o">)</span>
<span class="n">except</span><span class="w"> </span><span class="n">SomeException</span><span class="w"> </span><span class="k">as</span><span class="w"> </span><span class="n">the_exception</span><span class="o">:</span>
<span class="w">    </span><span class="n">handle_SomeException</span><span class="o">(</span><span class="n">the_exception</span><span class="o">)</span>
<span class="w">    </span><span class="err">#</span><span class="w"> </span><span class="n">Handle</span><span class="w"> </span><span class="n">a</span><span class="w"> </span><span class="n">instance</span><span class="w"> </span><span class="n">of</span><span class="w"> </span><span class="n">SomeException</span><span class="w"> </span><span class="n">or</span><span class="w"> </span><span class="n">a</span><span class="w"> </span><span class="n">subclass</span><span class="w"> </span><span class="n">of</span><span class="w"> </span><span class="n">it</span><span class="o">.</span>
<span class="n">except</span><span class="w"> </span><span class="n">Exception</span><span class="w"> </span><span class="k">as</span><span class="w"> </span><span class="n">the_exception</span><span class="o">:</span>
<span class="w">    </span><span class="n">generic_handle</span><span class="o">(</span><span class="n">the_exception</span><span class="o">)</span>
<span class="w">    </span><span class="err">#</span><span class="w"> </span><span class="n">Handle</span><span class="w"> </span><span class="n">any</span><span class="w"> </span><span class="n">other</span><span class="w"> </span><span class="n">exception</span><span class="w"> </span><span class="n">that</span><span class="w"> </span><span class="n">inherits</span><span class="w"> </span><span class="n">from</span><span class="w"> </span><span class="n">Exception</span>
<span class="w">    </span><span class="err">#</span><span class="w"> </span><span class="o">-</span><span class="w"> </span><span class="n">doesn</span><span class="s1">'t include GeneratorExit, KeyboardInterrupt, SystemExit</span>
<span class="s1">    # Avoid bare `except:`</span>
<span class="s1">else: # there was no exception whatsoever</span>
<span class="s1">    return something()</span>
<span class="s1">    # if no exception, the "something()" gets evaluated,</span>
<span class="s1">    # but the return will not be executed due to the return in the</span>
<span class="s1">    # finally block below.</span>
<span class="s1">finally:</span>
<span class="s1">    # this block will execute no matter what, even if no exception,</span>
<span class="s1">    # after "something" is eval'</span><span class="n">d</span><span class="w"> </span><span class="n">but</span><span class="w"> </span><span class="n">before</span><span class="w"> </span><span class="n">that</span><span class="w"> </span><span class="n">value</span><span class="w"> </span><span class="k">is</span><span class="w"> </span><span class="n">returned</span>
<span class="w">    </span><span class="err">#</span><span class="w"> </span><span class="n">but</span><span class="w"> </span><span class="n">even</span><span class="w"> </span><span class="k">if</span><span class="w"> </span><span class="n">there</span><span class="w"> </span><span class="k">is</span><span class="w"> </span><span class="n">an</span><span class="w"> </span><span class="n">exception</span><span class="o">.</span>
<span class="w">    </span><span class="err">#</span><span class="w"> </span><span class="n">a</span><span class="w"> </span><span class="k">return</span><span class="w"> </span><span class="n">here</span><span class="w"> </span><span class="n">will</span><span class="w"> </span><span class="n">hijack</span><span class="w"> </span><span class="n">the</span><span class="w"> </span><span class="k">return</span><span class="w"> </span><span class="n">functionality</span><span class="o">.</span><span class="w"> </span><span class="n">e</span><span class="o">.</span><span class="na">g</span><span class="o">.:</span>
<span class="w">    </span><span class="k">return</span><span class="w"> </span><span class="n">True</span><span class="w"> </span><span class="err">#</span><span class="w"> </span><span class="n">hijacks</span><span class="w"> </span><span class="n">the</span><span class="w"> </span><span class="k">return</span><span class="w"> </span><span class="k">in</span><span class="w"> </span><span class="n">the</span><span class="w"> </span><span class="k">else</span><span class="w"> </span><span class="n">clause</span><span class="w"> </span><span class="n">above</span>
</pre></div>

<p>It is true that we <em>could</em> include the code in the <code>else</code> block in the <code>try</code>
block instead, where it would run if there were no exceptions, but what if
that code itself raises an exception of the kind we're catching? Leaving it in
the <code>try</code> block would hide that bug.</p>
<p>We want to minimize lines of code in the <code>try</code> block to avoid catching
exceptions we did not expect, under the principle that if our code fails, we
want it to fail loudly. This is a best practice.</p>
<blockquote>
<h3>It is my understanding that exceptions are not errors</h3>
</blockquote>
<p>In Python, most exceptions are errors.</p>
<p>We can view the exception hierarchy by using pydoc. For example, in Python 2:</p>
<div class="code"><pre class="code literal-block">$<span class="w"> </span>python<span class="w"> </span>-m<span class="w"> </span>pydoc<span class="w"> </span>exceptions
</pre></div>

<p>or Python 3:</p>
<div class="code"><pre class="code literal-block">$<span class="w"> </span>python<span class="w"> </span>-m<span class="w"> </span>pydoc<span class="w"> </span>builtins
</pre></div>

<p>Will give us the hierarchy. We can see that most kinds of <code>Exception</code> are
errors, although Python uses some of them for things like ending <code>for</code> loops
(<code>StopIteration</code>). This is Python 3's hierarchy:</p>
<div class="code"><pre class="code literal-block"><span class="n">BaseException</span>
<span class="w">    </span><span class="n">Exception</span>
<span class="w">        </span><span class="n">ArithmeticError</span>
<span class="w">            </span><span class="n">FloatingPointError</span>
<span class="w">            </span><span class="n">OverflowError</span>
<span class="w">            </span><span class="n">ZeroDivisionError</span>
<span class="w">        </span><span class="n">AssertionError</span>
<span class="w">        </span><span class="n">AttributeError</span>
<span class="w">        </span><span class="n">BufferError</span>
<span class="w">        </span><span class="n">EOFError</span>
<span class="w">        </span><span class="n">ImportError</span>
<span class="w">            </span><span class="n">ModuleNotFoundError</span>
<span class="w">        </span><span class="n">LookupError</span>
<span class="w">            </span><span class="n">IndexError</span>
<span class="w">            </span><span class="n">KeyError</span>
<span class="w">        </span><span class="n">MemoryError</span>
<span class="w">        </span><span class="n">NameError</span>
<span class="w">            </span><span class="n">UnboundLocalError</span>
<span class="w">        </span><span class="n">OSError</span>
<span class="w">            </span><span class="n">BlockingIOError</span>
<span class="w">            </span><span class="n">ChildProcessError</span>
<span class="w">            </span><span class="n">ConnectionError</span>
<span class="w">                </span><span class="n">BrokenPipeError</span>
<span class="w">                </span><span class="n">ConnectionAbortedError</span>
<span class="w">                </span><span class="n">ConnectionRefusedError</span>
<span class="w">                </span><span class="n">ConnectionResetError</span>
<span class="w">            </span><span class="n">FileExistsError</span>
<span class="w">            </span><span class="n">FileNotFoundError</span>
<span class="w">            </span><span class="n">InterruptedError</span>
<span class="w">            </span><span class="n">IsADirectoryError</span>
<span class="w">            </span><span class="n">NotADirectoryError</span>
<span class="w">            </span><span class="n">PermissionError</span>
<span class="w">            </span><span class="n">ProcessLookupError</span>
<span class="w">            </span><span class="n">TimeoutError</span>
<span class="w">        </span><span class="n">ReferenceError</span>
<span class="w">        </span><span class="n">RuntimeError</span>
<span class="w">            </span><span class="n">NotImplementedError</span>
<span class="w">            </span><span class="n">RecursionError</span>
<span class="w">        </span><span class="n">StopAsyncIteration</span>
<span class="w">        </span><span class="n">StopIteration</span>
<span class="w">        </span><span class="n">SyntaxError</span>
<span class="w">            </span><span class="n">IndentationError</span>
<span class="w">                </span><span class="n">TabError</span>
<span class="w">        </span><span class="n">SystemError</span>
<span class="w">        </span><span class="n">TypeError</span>
<span class="w">        </span><span class="n">ValueError</span>
<span class="w">            </span><span class="n">UnicodeError</span>
<span class="w">                </span><span class="n">UnicodeDecodeError</span>
<span class="w">                </span><span class="n">UnicodeEncodeError</span>
<span class="w">                </span><span class="n">UnicodeTranslateError</span>
<span class="w">        </span><span class="n">Warning</span>
<span class="w">            </span><span class="n">BytesWarning</span>
<span class="w">            </span><span class="n">DeprecationWarning</span>
<span class="w">            </span><span class="n">FutureWarning</span>
<span class="w">            </span><span class="n">ImportWarning</span>
<span class="w">            </span><span class="n">PendingDeprecationWarning</span>
<span class="w">            </span><span class="n">ResourceWarning</span>
<span class="w">            </span><span class="n">RuntimeWarning</span>
<span class="w">            </span><span class="n">SyntaxWarning</span>
<span class="w">            </span><span class="n">UnicodeWarning</span>
<span class="w">            </span><span class="n">UserWarning</span>
<span class="w">    </span><span class="n">GeneratorExit</span>
<span class="w">    </span><span class="n">KeyboardInterrupt</span>
<span class="w">    </span><span class="n">SystemExit</span>
</pre></div>

<p>A commenter asked:</p>
<blockquote>
<p>Say you have a method which pings an external API and you want to handle the
exception at a class outside the API wrapper, do you simply return e from
the method under the except clause where e is the exception object?</p>
</blockquote>
<p>No, you don't return the exception, just reraise it with a bare <code>raise</code> to
preserve the stacktrace.</p>
<div class="code"><pre class="code literal-block"><span class="k">try</span><span class="o">:</span>
<span class="w">    </span><span class="n">try_this</span><span class="o">(</span><span class="n">whatever</span><span class="o">)</span>
<span class="n">except</span><span class="w"> </span><span class="n">SomeException</span><span class="w"> </span><span class="k">as</span><span class="w"> </span><span class="n">the_exception</span><span class="o">:</span>
<span class="w">    </span><span class="n">handle</span><span class="o">(</span><span class="n">the_exception</span><span class="o">)</span>
<span class="w">    </span><span class="n">raise</span>
</pre></div>

<p>Or, in Python 3, you can raise a new exception and preserve the backtrace with
exception chaining:</p>
<div class="code"><pre class="code literal-block"><span class="k">try</span><span class="o">:</span>
<span class="w">    </span><span class="n">try_this</span><span class="o">(</span><span class="n">whatever</span><span class="o">)</span>
<span class="n">except</span><span class="w"> </span><span class="n">SomeException</span><span class="w"> </span><span class="k">as</span><span class="w"> </span><span class="n">the_exception</span><span class="o">:</span>
<span class="w">    </span><span class="n">handle</span><span class="o">(</span><span class="n">the_exception</span><span class="o">)</span>
<span class="w">    </span><span class="n">raise</span><span class="w"> </span><span class="n">DifferentException</span><span class="w"> </span><span class="n">from</span><span class="w"> </span><span class="n">the_exception</span>
</pre></div>

<p>I elaborate in my answer here.</p>
    </div>
    <aside class="postpromonav"><nav><ul itemprop="keywords" class="tags">
<li><a class="tag p-category" href="../../categories/exception/" rel="tag">exception</a></li>
            <li><a class="tag p-category" href="../../categories/python/" rel="tag">python</a></li>
            <li><a class="tag p-category" href="../../categories/try-catch/" rel="tag">try-catch</a></li>
        </ul>
<ul class="pager hidden-print">
<li class="previous">
                <a href="../mongod-complains-that-there-is-no-data-db-folder/" rel="prev" title="Mongod complains that there is no /data/db folder">Previous post</a>
            </li>
            <li class="next">
                <a href="../how-do-i-find-the-time-difference-between-two-datetime-objects-in-python/" rel="next" title="How do I find the time difference between two datetime objects in python?">Next post</a>
            </li>
        </ul></nav></aside></article>
</div>
        <!--End of body content-->

        <footer id="footer">
            Contents © 2023         Go to StackOverflow Chinese Site  <a href="http://stackoverflow.ink">StackOverflow中文网</a>  
            
        </footer>
</div>
</div>


            <script src="../../assets/js/all-nocdn.js"></script><!-- fancy dates --><script>
    moment.locale("en");
    fancydates(0, "YYYY-MM-DD HH:mm");
    </script><!-- end fancy dates --><script>
    baguetteBox.run('div#content', {
        ignoreClass: 'islink',
        captions: function(element) {
            return element.getElementsByTagName('img')[0].alt;
    }});
    </script><script src="../../assets/js/search.js"></script>
</body>
</html>
