<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>How to properly assert that an exception gets raised in pytest? | StackOverflow Snapshot</title>
<link href="../../assets/css/all-nocdn.css" rel="stylesheet" type="text/css">
<meta name="theme-color" content="#5670d4">
<meta name="generator" content="Nikola (getnikola.com)">
<link rel="canonical" href="https://ohstackoverflow.netlify.app/posts/how-to-properly-assert-that-an-exception-gets-raised-in-pytest/">
<!--[if lt IE 9]><script src="../../assets/js/html5.js"></script><![endif]--><meta name="author" content="Arya">
<link rel="prev" href="../difference-between-dom-parentnode-and-parentelement/" title="Difference between DOM parentNode and parentElement" type="text/html">
<link rel="next" href="../how-can-i-use-grep-to-find-a-word-inside-a-folder/" title="How can I use grep to find a word inside a folder?" type="text/html">
<meta property="og:site_name" content="StackOverflow Snapshot">
<meta property="og:title" content="How to properly assert that an exception gets raised in pytest?">
<meta property="og:url" content="https://ohstackoverflow.netlify.app/posts/how-to-properly-assert-that-an-exception-gets-raised-in-pytest/">
<meta property="og:description" content="Code:
# coding=utf-8
import pytest


def whatever():
    return 9/0

def test_whatever():
    try:
        whatever()
    except ZeroDivisionError as exc:
        pytest.fail(exc, pytrace=True)


Outp">
<meta property="og:type" content="article">
<meta property="article:published_time" content="2023-02-17T18:23:56+08:00">
<meta property="article:tag" content="pytest">
<meta property="article:tag" content="python">
<meta property="article:tag" content="testing">
<meta property="article:tag" content="unit-testing">
</head>
<body>
<a href="#content" class="sr-only sr-only-focusable">Skip to main content</a>

<!-- Menubar -->

<nav class="navbar navbar-inverse navbar-static-top"><div class="container">
<!-- This keeps the margins nice -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar" aria-controls="bs-navbar" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="https://ohstackoverflow.netlify.app/">

                <span id="blog-title">StackOverflow Snapshot</span>
            </a>
        </div>
<!-- /.navbar-header -->
        <div class="collapse navbar-collapse" id="bs-navbar" aria-expanded="false">
            <ul class="nav navbar-nav">
<li>
<a href="../../archive.html">Archive</a>
                </li>
<li>
<a href="../../categories/">Tags</a>

                
            </li>
</ul>
<ul class="nav navbar-nav navbar-right">
<div style="display:table;min-height:5rem;min-width:27rem;">
					<div class="input-group" style="display: table-cell;vertical-align: middle;">
						<input id="words" type="text" class="form-control" style="max-width:22rem;" onkeydown="if(event.keyCode==13){btn.click()}"><span class="input-group-btn" style="float:left">
							<button id="btn" class="btn btn-default" type="button" data-toggle="modal" data-target="#myModal">
								<span class="glyphicon glyphicon-search">
							</span></button>
						</span>
					</div>
<!-- /input-group -->
				</div>

				
                
                
                
            </ul>
</div>
<!-- /.navbar-collapse -->
    </div>
<!-- /.container -->
</nav><!-- End of Menubar --><!-- 模态框（Modal） --><div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×
				</button>
				<h4 class="modal-title" id="myModalLabel">
					查找结果
				</h4>
			</div>
			<div class="modal-body">
				<div id="search-count" style="min-height:4rem;">
				查找中，请稍后...
				</div>
				<div id="search-result">
				</div>

				
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">
					关闭
				</button>
			</div>
		</div>
<!-- /.modal-content -->
	</div>
<!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="container" id="content" role="main">
    <div class="body-content">
        <!--Body content-->
        <div class="row">
            
            
<article class="post-text h-entry hentry postpage" itemscope="itemscope" itemtype="http://schema.org/Article"><header><h1 class="p-name entry-title" itemprop="headline name"><a href="." class="u-url">How to properly assert that an exception gets raised in pytest?</a></h1>

        <div class="metadata">
            <p class="byline author vcard p-author h-card"><span class="byline-name fn p-name" itemprop="author">
                    <a class="u-url" href="../../authors/arya/">Arya</a>
            </span></p>
            <p class="dateline">
            <a href="." rel="bookmark">
            <time class="published dt-published" datetime="2023-02-17T18:23:56+08:00" itemprop="datePublished" title="2023-02-17 18:23">2023-02-17 18:23</time></a>
            </p>
            

        </div>
        

    </header><div class="e-content entry-content" itemprop="articleBody text">
    <h3>Code:</h3>
<div class="code"><pre class="code literal-block"><span class="c1"># coding=utf-8</span>
<span class="kn">import</span> <span class="nn">pytest</span>


<span class="k">def</span> <span class="nf">whatever</span><span class="p">():</span>
    <span class="k">return</span> <span class="mi">9</span><span class="o">/</span><span class="mi">0</span>

<span class="k">def</span> <span class="nf">test_whatever</span><span class="p">():</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="n">whatever</span><span class="p">()</span>
    <span class="k">except</span> <span class="ne">ZeroDivisionError</span> <span class="k">as</span> <span class="n">exc</span><span class="p">:</span>
        <span class="n">pytest</span><span class="o">.</span><span class="n">fail</span><span class="p">(</span><span class="n">exc</span><span class="p">,</span> <span class="n">pytrace</span><span class="o">=</span><span class="kc">True</span><span class="p">)</span>
</pre></div>

<h3>Output:</h3>
<div class="code"><pre class="code literal-block">================================ test session starts =================================
platform linux2 -- Python 2.7.3 -- py-1.4.20 -- pytest-2.5.2
plugins: django, cov
collected 1 items

pytest_test.py F

====================================== FAILURES ======================================
___________________________________ test_whatever ____________________________________

    def test_whatever():
        try:
            whatever()
        except ZeroDivisionError as exc:
&gt;           pytest.fail(exc, pytrace=True)
E           Failed: integer division or modulo by zero

pytest_test.py:12: Failed
============================== 1 failed in 1.16 seconds ==============================
</pre></div>

<p>How to make pytest print traceback, so I would see where in the <code>whatever</code>
function an exception was raised?</p>
<p><br><br></p>
<h2>Answer</h2>
<p><code>pytest.raises(Exception)</code> is what you need.</p>
<p><strong>Code</strong></p>
<div class="code"><pre class="code literal-block"><span class="kn">import</span> <span class="nn">pytest</span>

<span class="k">def</span> <span class="nf">test_passes</span><span class="p">():</span>
    <span class="k">with</span> <span class="n">pytest</span><span class="o">.</span><span class="n">raises</span><span class="p">(</span><span class="ne">Exception</span><span class="p">)</span> <span class="k">as</span> <span class="n">e_info</span><span class="p">:</span>
        <span class="n">x</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">/</span> <span class="mi">0</span>

<span class="k">def</span> <span class="nf">test_passes_without_info</span><span class="p">():</span>
    <span class="k">with</span> <span class="n">pytest</span><span class="o">.</span><span class="n">raises</span><span class="p">(</span><span class="ne">Exception</span><span class="p">):</span>
        <span class="n">x</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">/</span> <span class="mi">0</span>

<span class="k">def</span> <span class="nf">test_fails</span><span class="p">():</span>
    <span class="k">with</span> <span class="n">pytest</span><span class="o">.</span><span class="n">raises</span><span class="p">(</span><span class="ne">Exception</span><span class="p">)</span> <span class="k">as</span> <span class="n">e_info</span><span class="p">:</span>
        <span class="n">x</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">/</span> <span class="mi">1</span>

<span class="k">def</span> <span class="nf">test_fails_without_info</span><span class="p">():</span>
    <span class="k">with</span> <span class="n">pytest</span><span class="o">.</span><span class="n">raises</span><span class="p">(</span><span class="ne">Exception</span><span class="p">):</span>
        <span class="n">x</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">/</span> <span class="mi">1</span>

<span class="c1"># Don't do this. Assertions are caught as exceptions.</span>
<span class="k">def</span> <span class="nf">test_passes_but_should_not</span><span class="p">():</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="n">x</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">/</span> <span class="mi">1</span>
        <span class="k">assert</span> <span class="kc">False</span>
    <span class="k">except</span> <span class="ne">Exception</span><span class="p">:</span>
        <span class="k">assert</span> <span class="kc">True</span>

<span class="c1"># Even if the appropriate exception is caught, it is bad style,</span>
<span class="c1"># because the test result is less informative</span>
<span class="c1"># than it would be with pytest.raises(e)</span>
<span class="c1"># (it just says pass or fail.)</span>

<span class="k">def</span> <span class="nf">test_passes_but_bad_style</span><span class="p">():</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="n">x</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">/</span> <span class="mi">0</span>
        <span class="k">assert</span> <span class="kc">False</span>
    <span class="k">except</span> <span class="ne">ZeroDivisionError</span><span class="p">:</span>
        <span class="k">assert</span> <span class="kc">True</span>

<span class="k">def</span> <span class="nf">test_fails_but_bad_style</span><span class="p">():</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="n">x</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">/</span> <span class="mi">1</span>
        <span class="k">assert</span> <span class="kc">False</span>
    <span class="k">except</span> <span class="ne">ZeroDivisionError</span><span class="p">:</span>
        <span class="k">assert</span> <span class="kc">True</span>
</pre></div>

<p><strong>Output</strong></p>
<div class="code"><pre class="code literal-block">============================================================================================= test session starts ==============================================================================================
platform linux2 -- Python 2.7.6 -- py-1.4.26 -- pytest-2.6.4
collected 7 items

test.py ..FF..F

=================================================================================================== FAILURES ===================================================================================================
__________________________________________________________________________________________________ test_fails __________________________________________________________________________________________________

    def test_fails():
        with pytest.raises(Exception) as e_info:
&gt;           x = 1 / 1
E           Failed: DID NOT RAISE

test.py:13: Failed
___________________________________________________________________________________________ test_fails_without_info ____________________________________________________________________________________________

    def test_fails_without_info():
        with pytest.raises(Exception):
&gt;           x = 1 / 1
E           Failed: DID NOT RAISE

test.py:17: Failed
___________________________________________________________________________________________ test_fails_but_bad_style ___________________________________________________________________________________________

    def test_fails_but_bad_style():
        try:
            x = 1 / 1
&gt;           assert False
E           assert False

test.py:43: AssertionError
====================================================================================== 3 failed, 4 passed in 0.02 seconds ======================================================================================
</pre></div>

<p>Note that <code>e_info</code> saves the exception object so you can extract details from
it. For example, if you want to check the exception call stack or another
nested exception inside.</p>
<p><br></p>
<h3>Suggest</h3>
<p>Do you mean something like this:</p>
<div class="code"><pre class="code literal-block"><span class="nt">def</span><span class="w"> </span><span class="nt">test_raises</span><span class="o">():</span>
<span class="w">    </span><span class="nt">with</span><span class="w"> </span><span class="nt">pytest</span><span class="p">.</span><span class="nc">raises</span><span class="o">(</span><span class="nt">Exception</span><span class="o">)</span><span class="w"> </span><span class="nt">as</span><span class="w"> </span><span class="nt">exc_info</span><span class="o">:</span><span class="w">   </span>
<span class="w">        </span><span class="nt">raise</span><span class="w"> </span><span class="nt">Exception</span><span class="o">(</span><span class="s1">'some info'</span><span class="o">)</span>
<span class="w">    </span><span class="err">#</span><span class="w"> </span><span class="nt">these</span><span class="w"> </span><span class="nt">asserts</span><span class="w"> </span><span class="nt">are</span><span class="w"> </span><span class="nt">identical</span><span class="o">;</span><span class="w"> </span><span class="nt">you</span><span class="w"> </span><span class="nt">can</span><span class="w"> </span><span class="nt">use</span><span class="w"> </span><span class="nt">either</span><span class="w"> </span><span class="nt">one</span><span class="w">   </span>
<span class="w">    </span><span class="nt">assert</span><span class="w"> </span><span class="nt">exc_info</span><span class="p">.</span><span class="nc">value</span><span class="p">.</span><span class="nc">args</span><span class="cp">[</span><span class="mi">0</span><span class="cp">]</span><span class="w"> </span><span class="o">==</span><span class="w"> </span><span class="s1">'some info'</span>
<span class="w">    </span><span class="nt">assert</span><span class="w"> </span><span class="nt">str</span><span class="o">(</span><span class="nt">exc_info</span><span class="p">.</span><span class="nc">value</span><span class="o">)</span><span class="w"> </span><span class="o">==</span><span class="w"> </span><span class="s1">'some info'</span>
</pre></div>
    </div>
    <aside class="postpromonav"><nav><ul itemprop="keywords" class="tags">
<li><a class="tag p-category" href="../../categories/pytest/" rel="tag">pytest</a></li>
            <li><a class="tag p-category" href="../../categories/python/" rel="tag">python</a></li>
            <li><a class="tag p-category" href="../../categories/testing/" rel="tag">testing</a></li>
            <li><a class="tag p-category" href="../../categories/unit-testing/" rel="tag">unit-testing</a></li>
        </ul>
<ul class="pager hidden-print">
<li class="previous">
                <a href="../difference-between-dom-parentnode-and-parentelement/" rel="prev" title="Difference between DOM parentNode and parentElement">Previous post</a>
            </li>
            <li class="next">
                <a href="../how-can-i-use-grep-to-find-a-word-inside-a-folder/" rel="next" title="How can I use grep to find a word inside a folder?">Next post</a>
            </li>
        </ul></nav></aside></article>
</div>
        <!--End of body content-->

        <footer id="footer">
            Contents © 2023         Go to StackOverflow Chinese Site  <a href="http://stackoverflow.ink">StackOverflow-ZH</a>  
            
        </footer>
</div>
</div>


            <script src="../../assets/js/all-nocdn.js"></script><!-- fancy dates --><script>
    moment.locale("en");
    fancydates(0, "YYYY-MM-DD HH:mm");
    </script><!-- end fancy dates --><script>
    baguetteBox.run('div#content', {
        ignoreClass: 'islink',
        captions: function(element) {
            return element.getElementsByTagName('img')[0].alt;
    }});
    </script><script src="../../assets/js/search.js"></script>
</body>
</html>
