<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Why catch and rethrow an exception in C#? | StackOverflow Snapshot</title>
<link href="../../assets/css/all-nocdn.css" rel="stylesheet" type="text/css">
<meta name="theme-color" content="#5670d4">
<meta name="generator" content="Nikola (getnikola.com)">
<link rel="canonical" href="https://ohstackoverflow.netlify.app/posts/why-catch-and-rethrow-an-exception-in-c/">
<!--[if lt IE 9]><script src="../../assets/js/html5.js"></script><![endif]--><meta name="author" content="Arya">
<link rel="prev" href="../yaml-do-i-need-quotes-for-strings-in-yaml/" title="YAML: Do I need quotes for strings in YAML?" type="text/html">
<link rel="next" href="../the-shortest-possible-output-from-git-log-containing-author-and-date/" title="The shortest possible output from git log containing author and date" type="text/html">
<meta property="og:site_name" content="StackOverflow Snapshot">
<meta property="og:title" content="Why catch and rethrow an exception in C#?">
<meta property="og:url" content="https://ohstackoverflow.netlify.app/posts/why-catch-and-rethrow-an-exception-in-c/">
<meta property="og:description" content="I'm looking at the article C# - Data Transfer Object on serializable DTOs.
The article includes this piece of code:
public static string SerializeDTO(DTO dto) {
    try {
        XmlSerializer xmlSer ">
<meta property="og:type" content="article">
<meta property="article:published_time" content="2023-02-17T18:05:33+08:00">
<meta property="article:tag" content=".net-c#">
<meta property="article:tag" content="exception">
<meta property="article:tag" content="try-catch">
</head>
<body>
<a href="#content" class="sr-only sr-only-focusable">Skip to main content</a>

<!-- Menubar -->

<nav class="navbar navbar-inverse navbar-static-top"><div class="container">
<!-- This keeps the margins nice -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar" aria-controls="bs-navbar" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="https://ohstackoverflow.netlify.app/">

                <span id="blog-title">StackOverflow Snapshot</span>
            </a>
        </div>
<!-- /.navbar-header -->
        <div class="collapse navbar-collapse" id="bs-navbar" aria-expanded="false">
            <ul class="nav navbar-nav">
<li>
<a href="../../archive.html">Archive</a>
                </li>
<li>
<a href="../../categories/">Tags</a>

                
            </li>
</ul>
<ul class="nav navbar-nav navbar-right">
<div style="display:table;min-height:5rem;min-width:27rem;">
					<div class="input-group" style="display: table-cell;vertical-align: middle;">
						<input id="words" type="text" class="form-control" style="max-width:22rem;" onkeydown="if(event.keyCode==13){btn.click()}"><span class="input-group-btn" style="float:left">
							<button id="btn" class="btn btn-default" type="button" data-toggle="modal" data-target="#myModal">
								<span class="glyphicon glyphicon-search">
							</span></button>
						</span>
					</div>
<!-- /input-group -->
				</div>

				
                
                
                
            </ul>
</div>
<!-- /.navbar-collapse -->
    </div>
<!-- /.container -->
</nav><!-- End of Menubar --><!-- 模态框（Modal） --><div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×
				</button>
				<h4 class="modal-title" id="myModalLabel">
					查找结果
				</h4>
			</div>
			<div class="modal-body">
				<div id="search-count" style="min-height:4rem;">
				查找中，请稍后...
				</div>
				<div id="search-result">
				</div>

				
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">
					关闭
				</button>
			</div>
		</div>
<!-- /.modal-content -->
	</div>
<!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="container" id="content" role="main">
    <div class="body-content">
        <!--Body content-->
        <div class="row">
            
            
<article class="post-text h-entry hentry postpage" itemscope="itemscope" itemtype="http://schema.org/Article"><header><h1 class="p-name entry-title" itemprop="headline name"><a href="." class="u-url">Why catch and rethrow an exception in C#?</a></h1>

        <div class="metadata">
            <p class="byline author vcard p-author h-card"><span class="byline-name fn p-name" itemprop="author">
                    <a class="u-url" href="../../authors/arya/">Arya</a>
            </span></p>
            <p class="dateline">
            <a href="." rel="bookmark">
            <time class="published dt-published" datetime="2023-02-17T18:05:33+08:00" itemprop="datePublished" title="2023-02-17 18:05">2023-02-17 18:05</time></a>
            </p>
            

        </div>
        

    </header><div class="e-content entry-content" itemprop="articleBody text">
    <p>I'm looking at the article <em>C# - Data Transfer Object</em> on serializable DTOs.</p>
<p>The article includes this piece of code:</p>
<div class="code"><pre class="code literal-block"><span class="nv">public</span><span class="w"> </span><span class="nv">static</span><span class="w"> </span><span class="nv">string</span><span class="w"> </span><span class="nv">SerializeDTO</span><span class="ss">(</span><span class="nv">DTO</span><span class="w"> </span><span class="nv">dto</span><span class="ss">)</span><span class="w"> </span>{
<span class="w">    </span><span class="nv">try</span><span class="w"> </span>{
<span class="w">        </span><span class="nv">XmlSerializer</span><span class="w"> </span><span class="nv">xmlSer</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="nv">new</span><span class="w"> </span><span class="nv">XmlSerializer</span><span class="ss">(</span><span class="nv">dto</span>.<span class="nv">GetType</span><span class="ss">())</span><span class="c1">;</span>
<span class="w">        </span><span class="nv">StringWriter</span><span class="w"> </span><span class="nv">sWriter</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="nv">new</span><span class="w"> </span><span class="nv">StringWriter</span><span class="ss">()</span><span class="c1">;</span>
<span class="w">        </span><span class="nv">xmlSer</span>.<span class="nv">Serialize</span><span class="ss">(</span><span class="nv">sWriter</span>,<span class="w"> </span><span class="nv">dto</span><span class="ss">)</span><span class="c1">;</span>
<span class="w">        </span><span class="k">return</span><span class="w"> </span><span class="nv">sWriter</span>.<span class="nv">ToString</span><span class="ss">()</span><span class="c1">;</span>
<span class="w">    </span>}
<span class="w">    </span><span class="nv">catch</span><span class="ss">(</span><span class="nv">Exception</span><span class="w"> </span><span class="nv">ex</span><span class="ss">)</span><span class="w"> </span>{
<span class="w">        </span><span class="nv">throw</span><span class="w"> </span><span class="nv">ex</span><span class="c1">;</span>
<span class="w">    </span>}
}
</pre></div>

<p>The rest of the article looks sane and reasonable (to a noob), but that try-
catch-throw throws a WtfException... <strong>Isn't this exactly equivalent to not
handling exceptions at all?</strong></p>
<p>Ergo:</p>
<div class="code"><pre class="code literal-block"><span class="nv">public</span><span class="w"> </span><span class="nv">static</span><span class="w"> </span><span class="nv">string</span><span class="w"> </span><span class="nv">SerializeDTO</span><span class="ss">(</span><span class="nv">DTO</span><span class="w"> </span><span class="nv">dto</span><span class="ss">)</span><span class="w"> </span>{
<span class="w">    </span><span class="nv">XmlSerializer</span><span class="w"> </span><span class="nv">xmlSer</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="nv">new</span><span class="w"> </span><span class="nv">XmlSerializer</span><span class="ss">(</span><span class="nv">dto</span>.<span class="nv">GetType</span><span class="ss">())</span><span class="c1">;</span>
<span class="w">    </span><span class="nv">StringWriter</span><span class="w"> </span><span class="nv">sWriter</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="nv">new</span><span class="w"> </span><span class="nv">StringWriter</span><span class="ss">()</span><span class="c1">;</span>
<span class="w">    </span><span class="nv">xmlSer</span>.<span class="nv">Serialize</span><span class="ss">(</span><span class="nv">sWriter</span>,<span class="w"> </span><span class="nv">dto</span><span class="ss">)</span><span class="c1">;</span>
<span class="w">    </span><span class="k">return</span><span class="w"> </span><span class="nv">sWriter</span>.<span class="nv">ToString</span><span class="ss">()</span><span class="c1">;</span>
}
</pre></div>

<p>Or am I missing something fundamental about error handling in C#? It's pretty
much the same as Java (minus checked exceptions), isn't it? ... That is, they
both refined C++.</p>
<p>The Stack Overflow question <em>The difference between re-throwing parameter-less
catch and not doing anything?</em> seems to support my contention that try-catch-
throw is-a no-op.</p>
<hr>
<p><strong>EDIT:</strong></p>
<p>Just to summarise for anyone who finds this thread in future...</p>
<p><strong>DO NOT</strong></p>
<div class="code"><pre class="code literal-block"><span class="nv">try</span><span class="w"> </span>{
<span class="w">    </span><span class="o">//</span><span class="w"> </span><span class="k">Do</span><span class="w"> </span><span class="nv">stuff</span><span class="w"> </span><span class="nv">that</span><span class="w"> </span><span class="nv">might</span><span class="w"> </span><span class="nv">throw</span><span class="w"> </span><span class="nv">an</span><span class="w"> </span><span class="nv">exception</span>
}
<span class="nv">catch</span><span class="w"> </span><span class="ss">(</span><span class="nv">Exception</span><span class="w"> </span><span class="nv">e</span><span class="ss">)</span><span class="w"> </span>{
<span class="w">    </span><span class="nv">throw</span><span class="w"> </span><span class="nv">e</span><span class="c1">; // This destroys the strack trace information!</span>
}
</pre></div>

<p>The stack trace information can be crucial to identifying the root cause of
the problem!</p>
<p><strong>DO</strong></p>
<div class="code"><pre class="code literal-block"><span class="nv">try</span><span class="w"> </span>{
<span class="w">    </span><span class="o">//</span><span class="w"> </span><span class="k">Do</span><span class="w"> </span><span class="nv">stuff</span><span class="w"> </span><span class="nv">that</span><span class="w"> </span><span class="nv">might</span><span class="w"> </span><span class="nv">throw</span><span class="w"> </span><span class="nv">an</span><span class="w"> </span><span class="nv">exception</span>
}
<span class="nv">catch</span><span class="w"> </span><span class="ss">(</span><span class="nv">SqlException</span><span class="w"> </span><span class="nv">e</span><span class="ss">)</span><span class="w"> </span>{
<span class="w">    </span><span class="o">//</span><span class="w"> </span><span class="nv">Log</span><span class="w"> </span><span class="nv">it</span>
<span class="w">    </span><span class="k">if</span><span class="w"> </span><span class="ss">(</span><span class="nv">e</span>.<span class="nv">ErrorCode</span><span class="w"> </span><span class="o">!=</span><span class="w"> </span><span class="nv">NO_ROW_ERROR</span><span class="ss">)</span><span class="w"> </span>{<span class="w"> </span><span class="o">//</span><span class="w"> </span><span class="nv">filter</span><span class="w"> </span><span class="nv">out</span><span class="w"> </span><span class="nv">NoDataFound</span>.
<span class="w">        </span><span class="o">//</span><span class="w"> </span><span class="k">Do</span><span class="w"> </span><span class="nv">special</span><span class="w"> </span><span class="nv">cleanup</span>,<span class="w"> </span><span class="nv">like</span><span class="w"> </span><span class="nv">maybe</span><span class="w"> </span><span class="nv">closing</span><span class="w"> </span><span class="nv">the</span><span class="w"> </span><span class="s2">"dirty"</span><span class="w"> </span><span class="nv">database</span><span class="w"> </span><span class="nv">connection</span>.
<span class="w">        </span><span class="nv">throw</span><span class="c1">; // This preserves the stack trace</span>
<span class="w">    </span>}
}
<span class="nv">catch</span><span class="w"> </span><span class="ss">(</span><span class="nv">IOException</span><span class="w"> </span><span class="nv">e</span><span class="ss">)</span><span class="w"> </span>{
<span class="w">    </span><span class="o">//</span><span class="w"> </span><span class="nv">Log</span><span class="w"> </span><span class="nv">it</span>
<span class="w">    </span><span class="nv">throw</span><span class="c1">;</span>
}
<span class="nv">catch</span><span class="w"> </span><span class="ss">(</span><span class="nv">Exception</span><span class="w"> </span><span class="nv">e</span><span class="ss">)</span><span class="w"> </span>{
<span class="w">    </span><span class="o">//</span><span class="w"> </span><span class="nv">Log</span><span class="w"> </span><span class="nv">it</span>
<span class="w">    </span><span class="nv">throw</span><span class="w"> </span><span class="nv">new</span><span class="w"> </span><span class="nv">DAOException</span><span class="ss">(</span><span class="s2">"Excrement occurred"</span>,<span class="w"> </span><span class="nv">e</span><span class="ss">)</span><span class="c1">; // wrapped &amp; chained exceptions (just like java).</span>
}
<span class="nv">finally</span><span class="w"> </span>{
<span class="w">    </span><span class="o">//</span><span class="w"> </span><span class="nv">Normal</span><span class="w"> </span><span class="nv">clean</span><span class="w"> </span><span class="nv">goes</span><span class="w"> </span><span class="nv">here</span><span class="w"> </span><span class="ss">(</span><span class="nv">like</span><span class="w"> </span><span class="nv">closing</span><span class="w"> </span><span class="nv">open</span><span class="w"> </span><span class="nv">files</span><span class="ss">)</span>.
}
</pre></div>

<p>Catch the more specific exceptions before the less specific ones (just like
Java).</p>
<hr>
<p><strong>References:</strong></p>
<ul>
<li>MSDN - Exception Handling</li>
<li>MSDN - try-catch (C# Reference)</li>
</ul>
<p><br><br></p>
<h2>Answer</h2>
<p>First, the way that the code in the article does it is evil. <code>throw ex</code> will
reset the call stack in the exception to the point where this throw statement
is losing the information about where the exception actually was created.</p>
<p>Second, if you just catch and re-throw like that, I see no added value. The
code example above would be just as good (or, given the <code>throw ex</code> bit, even
better) without the try-catch.</p>
<p>However, there are cases where you might want to catch and rethrow an
exception. Logging could be one of them:</p>
<div class="code"><pre class="code literal-block">    try 
    {
        // code that may throw exceptions    
    }
    catch(Exception ex) 
    {
        // add error logging here
        throw;
    }
</pre></div>

<p><br></p>
<h3>Suggest</h3>
<p>Don't do this,</p>
<div class="code"><pre class="code literal-block">try 
{
...
}
catch(Exception ex)
{
   throw ex;
}
</pre></div>

<p>You'll lose the stack trace information...</p>
<p>Either do,</p>
<div class="code"><pre class="code literal-block">try { ... }
catch { throw; }
</pre></div>

<p>OR</p>
<div class="code"><pre class="code literal-block">try { ... }
catch (Exception ex)
{
    throw new Exception("My Custom Error Message", ex);
}
</pre></div>

<p>One of the reason you might want to rethrow is if you're handling different
exceptions, for e.g.</p>
<div class="code"><pre class="code literal-block"><span class="nv">try</span>
{
<span class="w">   </span>...
}
<span class="nv">catch</span><span class="ss">(</span><span class="nv">SQLException</span><span class="w"> </span><span class="nv">sex</span><span class="ss">)</span>
{
<span class="w">   </span><span class="o">//</span><span class="k">Do</span><span class="w"> </span><span class="nv">Custom</span><span class="w"> </span><span class="nv">Logging</span><span class="w"> </span>
<span class="w">   </span><span class="o">//</span><span class="nv">Don</span><span class="err">'t throw exception - swallow it here</span>
<span class="err">}</span>
<span class="err">catch(OtherException oex)</span>
<span class="err">{</span>
<span class="err">   //Do something else</span>
<span class="err">   throw new WrappedException("Other Exception occured");</span>
<span class="err">}</span>
<span class="err">catch</span>
<span class="err">{</span>
<span class="err">   System.Diagnostics.Debug.WriteLine("Eeep! an error, not to worry, will be handled higher up the call stack");</span>
<span class="err">   throw; //Chuck everything else back up the stack</span>
<span class="err">}</span>
</pre></div>
    </div>
    <aside class="postpromonav"><nav><ul itemprop="keywords" class="tags">
<li><a class="tag p-category" href="../../categories/net-c/" rel="tag">.net-c#</a></li>
            <li><a class="tag p-category" href="../../categories/exception/" rel="tag">exception</a></li>
            <li><a class="tag p-category" href="../../categories/try-catch/" rel="tag">try-catch</a></li>
        </ul>
<ul class="pager hidden-print">
<li class="previous">
                <a href="../yaml-do-i-need-quotes-for-strings-in-yaml/" rel="prev" title="YAML: Do I need quotes for strings in YAML?">Previous post</a>
            </li>
            <li class="next">
                <a href="../the-shortest-possible-output-from-git-log-containing-author-and-date/" rel="next" title="The shortest possible output from git log containing author and date">Next post</a>
            </li>
        </ul></nav></aside></article>
</div>
        <!--End of body content-->

        <footer id="footer">
            Contents © 2023         Go to StackOverflow Chinese Site  <a href="http://stackoverflow.ink">StackOverflow中文网</a>  
            
        </footer>
</div>
</div>


            <script src="../../assets/js/all-nocdn.js"></script><!-- fancy dates --><script>
    moment.locale("en");
    fancydates(0, "YYYY-MM-DD HH:mm");
    </script><!-- end fancy dates --><script>
    baguetteBox.run('div#content', {
        ignoreClass: 'islink',
        captions: function(element) {
            return element.getElementsByTagName('img')[0].alt;
    }});
    </script><script src="../../assets/js/search.js"></script>
</body>
</html>
