<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>在 Python 中使用 try-except-else 是一种好习惯吗？ | StackOverflow Snapshot</title>
<link href="../../assets/css/all-nocdn.css" rel="stylesheet" type="text/css">
<meta name="theme-color" content="#5670d4">
<meta name="generator" content="Nikola (getnikola.com)">
<link rel="canonical" href="https://ohstackoverflow.netlify.app/posts/zai-python-zhong-shi-yong-try-except-else-shi-yi-chong-hao-xi-guan-ma/">
<!--[if lt IE 9]><script src="../../assets/js/html5.js"></script><![endif]--><meta name="author" content="Arya">
<link rel="prev" href="../mongod-bao-yuan-mei-you-data-db-wen-jian-jia/" title="Mongod 抱怨没有 /data/db 文件夹" type="text/html">
<link rel="next" href="../ru-he-zhao-dao-python-zhong-liang-ge-datetime-dui-xiang-zhi-jian-de-shi-jian-chai/" title="如何找到 python 中两个 datetime 对象之间的时间差？" type="text/html">
<meta property="og:site_name" content="StackOverflow Snapshot">
<meta property="og:title" content="在 Python 中使用 try-except-else 是一种好习惯吗？">
<meta property="og:url" content="https://ohstackoverflow.netlify.app/posts/zai-python-zhong-shi-yong-try-except-else-shi-yi-chong-hao-xi-guan-ma/">
<meta property="og:description" content="有时在 Python 中，我会看到块：
try:
   try_this(whatever)
except SomeException as exception:
   #Handle exception
else:
   return something


try-except-else 存在的原因是什么？
我不喜欢那种编程，因为它使用异常来执行流程控制。但是，如果它包含在语言中，那一定有充分">
<meta property="og:type" content="article">
<meta property="article:published_time" content="2023-02-18T05:27:22+08:00">
<meta property="article:tag" content="exception">
<meta property="article:tag" content="python">
<meta property="article:tag" content="try-catch">
</head>
<body>
<a href="#content" class="sr-only sr-only-focusable">Skip to main content</a>

<!-- Menubar -->

<nav class="navbar navbar-inverse navbar-static-top"><div class="container">
<!-- This keeps the margins nice -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar" aria-controls="bs-navbar" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="https://ohstackoverflow.netlify.app/">

                <span id="blog-title">StackOverflow Snapshot</span>
            </a>
        </div>
<!-- /.navbar-header -->
        <div class="collapse navbar-collapse" id="bs-navbar" aria-expanded="false">
            <ul class="nav navbar-nav">
<li>
<a href="../../archive.html">Archive</a>
                </li>
<li>
<a href="../../categories/">Tags</a>

                
            </li>
</ul>
<ul class="nav navbar-nav navbar-right">
<div style="display:table;min-height:5rem;min-width:27rem;">
					<div class="input-group" style="display: table-cell;vertical-align: middle;">
						<input id="words" type="text" class="form-control" style="max-width:22rem;" onkeydown="if(event.keyCode==13){btn.click()}"><span class="input-group-btn" style="float:left">
							<button id="btn" class="btn btn-default" type="button" data-toggle="modal" data-target="#myModal">
								<span class="glyphicon glyphicon-search">
							</span></button>
						</span>
					</div>
<!-- /input-group -->
				</div>

				
                
                
                
            </ul>
</div>
<!-- /.navbar-collapse -->
    </div>
<!-- /.container -->
</nav><!-- End of Menubar --><!-- 模态框（Modal） --><div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×
				</button>
				<h4 class="modal-title" id="myModalLabel">
					查找结果
				</h4>
			</div>
			<div class="modal-body">
				<div id="search-count" style="min-height:4rem;">
				查找中，请稍后...
				</div>
				<div id="search-result">
				</div>

				
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">
					关闭
				</button>
			</div>
		</div>
<!-- /.modal-content -->
	</div>
<!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="container" id="content" role="main">
    <div class="body-content">
        <!--Body content-->
        <div class="row">
            
            
<article class="post-text h-entry hentry postpage" itemscope="itemscope" itemtype="http://schema.org/Article"><header><h1 class="p-name entry-title" itemprop="headline name"><a href="." class="u-url">在 Python 中使用 try-except-else 是一种好习惯吗？</a></h1>

        <div class="metadata">
            <p class="byline author vcard p-author h-card"><span class="byline-name fn p-name" itemprop="author">
                    <a class="u-url" href="../../authors/arya/">Arya</a>
            </span></p>
            <p class="dateline">
            <a href="." rel="bookmark">
            <time class="published dt-published" datetime="2023-02-18T05:27:22+08:00" itemprop="datePublished" title="2023-02-18 05:27">2023-02-18 05:27</time></a>
            </p>
            

        </div>
        

    </header><div class="e-content entry-content" itemprop="articleBody text">
    <p>有时在 Python 中，我会看到块：</p>
<div class="code"><pre class="code literal-block"><span class="k">try</span><span class="o">:</span>
<span class="w">   </span><span class="n">try_this</span><span class="o">(</span><span class="n">whatever</span><span class="o">)</span>
<span class="n">except</span><span class="w"> </span><span class="n">SomeException</span><span class="w"> </span><span class="k">as</span><span class="w"> </span><span class="n">exception</span><span class="o">:</span>
<span class="w">   </span><span class="err">#</span><span class="n">Handle</span><span class="w"> </span><span class="n">exception</span>
<span class="k">else</span><span class="o">:</span>
<span class="w">   </span><span class="k">return</span><span class="w"> </span><span class="n">something</span>
</pre></div>

<p><strong>try-except-else 存在的原因是什么？</strong></p>
<p>我不喜欢那种编程，因为它使用异常来执行流程控制。但是，如果它包含在语言中，那一定有充分的理由，不是吗？</p>
<p><strong>我的理解是异常不是错误</strong> ，它们应该只用于异常情况（例如，我尝试将文件写入磁盘但没有更多空间，或者我没有权限），而不是用于流程控制。</p>
<p>通常我将异常处理为：</p>
<div class="code"><pre class="code literal-block"><span class="nv">something</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="nv">some_default_value</span>
<span class="nv">try</span>:
<span class="w">    </span><span class="nv">something</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="nv">try_this</span><span class="ss">(</span><span class="nv">whatever</span><span class="ss">)</span>
<span class="nv">except</span><span class="w"> </span><span class="nv">SomeException</span><span class="w"> </span><span class="nv">as</span><span class="w"> </span><span class="nv">exception</span>:
<span class="w">    </span>#<span class="nv">Handle</span><span class="w"> </span><span class="nv">exception</span>
<span class="nv">finally</span>:
<span class="w">    </span><span class="k">return</span><span class="w"> </span><span class="nv">something</span>
</pre></div>

<p>或者如果发生异常我真的不想返回任何东西，那么：</p>
<div class="code"><pre class="code literal-block"><span class="k">try</span><span class="o">:</span>
<span class="w">    </span><span class="n">something</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="n">try_this</span><span class="o">(</span><span class="n">whatever</span><span class="o">)</span>
<span class="w">    </span><span class="k">return</span><span class="w"> </span><span class="n">something</span>
<span class="n">except</span><span class="w"> </span><span class="n">SomeException</span><span class="w"> </span><span class="k">as</span><span class="w"> </span><span class="n">exception</span><span class="o">:</span>
<span class="w">    </span><span class="err">#</span><span class="n">Handle</span><span class="w"> </span><span class="n">exception</span>
</pre></div>

<p><br><br></p>
<h2>解答</h2>
<blockquote>
<p>“不知道是不是孤陋寡闻，我不喜欢那种编程，就是用异常来进行流控。”</p>
</blockquote>
<p>在 Python 世界中，使用异常进行流控制是很常见的。</p>
<p>即使是 Python 核心开发人员也使用异常来进行流控制，并且这种风格在很大程度上融入了语言（即迭代器协议使用 <em>StopIteration</em>
来发出循环终止信号）。</p>
<p>此外，try-except-style 用于防止某些“先看后跳”结构中固有的竞争条件。例如，测试 <em>os.path.exists</em>
得到的信息在您使用时可能已经过时。同样， <em>Queue.full</em> 返回可能过时的信息。在这些情况下， try -except-else
风格将产生更可靠的代码。</p>
<blockquote>
<p>“我的理解是异常不是错误，它们应该只用于特殊情况”</p>
</blockquote>
<p>在其他一些语言中，该规则反映了其图书馆中反映的文化规范。“规则”也部分基于对这些语言的性能考虑。</p>
<p>Python 文化规范有些不同。在许多情况下，您 <em>必须</em> 为控制流使用异常。此外，在 Python
中使用异常不会像在某些编译语言中那样减慢周围代码和调用代码的速度（即CPython已经在每一步都实现了异常检查代码，无论您是否实际使用异常）。</p>
<p>换句话说，您对“异常是为了异常”的理解是一条在其他一些语言中有意义的规则，但在 Python 中则不然。</p>
<blockquote>
<p>“但是，如果它包含在语言本身中，那一定有充分的理由，不是吗？”</p>
</blockquote>
<p>除了有助于避免竞争条件外，异常对于将错误处理拉到外部循环也非常有用。这是解释性语言中的必要优化，因为解释性语言不倾向于具有自动循环不变代码运动。</p>
<p>此外，在处理问题的能力与问题发生的地方相去甚远的常见情况下，异常可以大大简化代码。例如，顶层用户界面代码调用业务逻辑代码是很常见的，而业务逻辑又调用低层例程。低级例程中出现的情况（例如数据库访问中唯一键的重复记录）只能在顶级代码中处理（例如要求用户提供与现有键不冲突的新键）。对这种控制流使用异常允许中级例程完全忽略该问题，并很好地与流控制的那个方面分离。</p>
<p>这里有一篇关于例外的必要性的不错的博客文章。</p>
<p>另外，请参阅 Stack Overflow 答案：Are exceptions really for exceptional errors?</p>
<blockquote>
<p>“try-except-else 存在的原因是什么？”</p>
</blockquote>
<p>else 子句本身很有趣。它在没有异常但在 finally 子句之前运行。这是它的主要目的。</p>
<p>如果没有 else 子句，在最终确定之前运行附加代码的唯一选择就是将代码添加到 try 子句的笨拙做法。这很笨拙，因为它冒着在不打算受 try
块保护的代码中引发异常的风险。</p>
<p>在完成之前运行额外的未受保护代码的用例并不经常出现。因此，不要期望在已发布的代码中看到很多示例。这有点罕见。</p>
<p>else 子句的另一个用例是执行在没有异常发生时必须发生并且在处理异常时不会发生的操作。例如：</p>
<div class="code"><pre class="code literal-block"><span class="nv">recip</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="nv">float</span><span class="ss">(</span><span class="s1">'Inf'</span><span class="ss">)</span>
<span class="nv">try</span>:
<span class="w">    </span><span class="nv">recip</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="mi">1</span><span class="w"> </span><span class="o">/</span><span class="w"> </span><span class="nv">f</span><span class="ss">(</span><span class="nv">x</span><span class="ss">)</span>
<span class="nv">except</span><span class="w"> </span><span class="nv">ZeroDivisionError</span>:
<span class="w">    </span><span class="nv">logging</span>.<span class="nv">info</span><span class="ss">(</span><span class="s1">'Infinite result'</span><span class="ss">)</span>
<span class="k">else</span>:
<span class="w">    </span><span class="nv">logging</span>.<span class="nv">info</span><span class="ss">(</span><span class="s1">'Finite result'</span><span class="ss">)</span>
</pre></div>

<p>另一个例子发生在单元测试运行器中：</p>
<div class="code"><pre class="code literal-block"><span class="k">try</span><span class="o">:</span>
<span class="w">    </span><span class="n">tests_run</span><span class="w"> </span><span class="o">+=</span><span class="w"> </span><span class="mi">1</span>
<span class="w">    </span><span class="n">run_testcase</span><span class="o">(</span><span class="k">case</span><span class="o">)</span>
<span class="n">except</span><span class="w"> </span><span class="n">Exception</span><span class="o">:</span>
<span class="w">    </span><span class="n">tests_failed</span><span class="w"> </span><span class="o">+=</span><span class="w"> </span><span class="mi">1</span>
<span class="w">    </span><span class="n">logging</span><span class="o">.</span><span class="na">exception</span><span class="o">(</span><span class="s1">'Failing test case: %r'</span><span class="o">,</span><span class="w"> </span><span class="k">case</span><span class="o">)</span>
<span class="w">    </span><span class="n">print</span><span class="o">(</span><span class="s1">'F'</span><span class="o">,</span><span class="w"> </span><span class="n">end</span><span class="o">=</span><span class="s1">''</span><span class="o">)</span>
<span class="k">else</span><span class="o">:</span>
<span class="w">    </span><span class="n">logging</span><span class="o">.</span><span class="na">info</span><span class="o">(</span><span class="s1">'Successful test case: %r'</span><span class="o">,</span><span class="w"> </span><span class="k">case</span><span class="o">)</span>
<span class="w">    </span><span class="n">print</span><span class="o">(</span><span class="s1">'.'</span><span class="o">,</span><span class="w"> </span><span class="n">end</span><span class="o">=</span><span class="s1">''</span><span class="o">)</span>
</pre></div>

<p>最后，在 try 块中 else 子句最常见的用途是进行一些美化（在同一缩进级别对齐异常结果和非异常结果）。这种使用总是可选的，并不是绝对必要的。</p>
<p><br></p>
<h3>更多建议</h3>
<blockquote>
<h3>try-except-else 存在的原因是什么？</h3>
</blockquote>
<p>块<code>try</code>允许您处理预期的错误。该<code>except</code>块应该只捕获您准备处理的异常。如果您处理意外错误，您的代码可能会做错事并隐藏错误。</p>
<p><code>else</code>如果没有错误，子句将执行，并且通过不在块中执行该代码，<code>try</code>可以避免捕获意外错误。同样，捕获意外错误可以隐藏错误。</p>
<h4>例子</h4>
<p>例如：</p>
<div class="code"><pre class="code literal-block"><span class="k">try</span><span class="o">:</span>
<span class="w">    </span><span class="n">try_this</span><span class="o">(</span><span class="n">whatever</span><span class="o">)</span>
<span class="n">except</span><span class="w"> </span><span class="n">SomeException</span><span class="w"> </span><span class="k">as</span><span class="w"> </span><span class="n">the_exception</span><span class="o">:</span>
<span class="w">    </span><span class="n">handle</span><span class="o">(</span><span class="n">the_exception</span><span class="o">)</span>
<span class="k">else</span><span class="o">:</span>
<span class="w">    </span><span class="k">return</span><span class="w"> </span><span class="n">something</span>
</pre></div>

<p>"try, except" 套件有两个可选子句，<code>else</code>和<code>finally</code>. 所以它实际上是<code>try-except-else-finally</code>。</p>
<p><code>else</code>只有在块中没有异常时才会评估<code>try</code>。它允许我们简化下面更复杂的代码：</p>
<div class="code"><pre class="code literal-block"><span class="nv">no_error</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="nv">None</span>
<span class="nv">try</span>:
<span class="w">    </span><span class="nv">try_this</span><span class="ss">(</span><span class="nv">whatever</span><span class="ss">)</span>
<span class="w">    </span><span class="nv">no_error</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="nv">True</span>
<span class="nv">except</span><span class="w"> </span><span class="nv">SomeException</span><span class="w"> </span><span class="nv">as</span><span class="w"> </span><span class="nv">the_exception</span>:
<span class="w">    </span><span class="nv">handle</span><span class="ss">(</span><span class="nv">the_exception</span><span class="ss">)</span>
<span class="k">if</span><span class="w"> </span><span class="nv">no_error</span>:
<span class="w">    </span><span class="k">return</span><span class="w"> </span><span class="nv">something</span>
</pre></div>

<p>因此，如果我们将 an<code>else</code>与替代方案（可能会产生错误）进行比较，我们会发现它减少了代码行，并且我们可以拥有更具可读性、可维护性和更少错误的代码库。</p>
<h4><code>finally</code></h4>
<p><code>finally</code>无论如何都会执行，即使正在使用 return 语句评估另一行。</p>
<h3>用伪代码分解</h3>
<p>它可能有助于以尽可能小的形式分解它，以展示所有功能，并附上评论。假设这个语法正确（但除非定义名称否则不可运行）伪代码在一个函数中。</p>
<p>例如：</p>
<div class="code"><pre class="code literal-block"><span class="k">try</span><span class="o">:</span>
<span class="w">    </span><span class="n">try_this</span><span class="o">(</span><span class="n">whatever</span><span class="o">)</span>
<span class="n">except</span><span class="w"> </span><span class="n">SomeException</span><span class="w"> </span><span class="k">as</span><span class="w"> </span><span class="n">the_exception</span><span class="o">:</span>
<span class="w">    </span><span class="n">handle_SomeException</span><span class="o">(</span><span class="n">the_exception</span><span class="o">)</span>
<span class="w">    </span><span class="err">#</span><span class="w"> </span><span class="n">Handle</span><span class="w"> </span><span class="n">a</span><span class="w"> </span><span class="n">instance</span><span class="w"> </span><span class="n">of</span><span class="w"> </span><span class="n">SomeException</span><span class="w"> </span><span class="n">or</span><span class="w"> </span><span class="n">a</span><span class="w"> </span><span class="n">subclass</span><span class="w"> </span><span class="n">of</span><span class="w"> </span><span class="n">it</span><span class="o">.</span>
<span class="n">except</span><span class="w"> </span><span class="n">Exception</span><span class="w"> </span><span class="k">as</span><span class="w"> </span><span class="n">the_exception</span><span class="o">:</span>
<span class="w">    </span><span class="n">generic_handle</span><span class="o">(</span><span class="n">the_exception</span><span class="o">)</span>
<span class="w">    </span><span class="err">#</span><span class="w"> </span><span class="n">Handle</span><span class="w"> </span><span class="n">any</span><span class="w"> </span><span class="n">other</span><span class="w"> </span><span class="n">exception</span><span class="w"> </span><span class="n">that</span><span class="w"> </span><span class="n">inherits</span><span class="w"> </span><span class="n">from</span><span class="w"> </span><span class="n">Exception</span>
<span class="w">    </span><span class="err">#</span><span class="w"> </span><span class="o">-</span><span class="w"> </span><span class="n">doesn</span><span class="s1">'t include GeneratorExit, KeyboardInterrupt, SystemExit</span>
<span class="s1">    # Avoid bare `except:`</span>
<span class="s1">else: # there was no exception whatsoever</span>
<span class="s1">    return something()</span>
<span class="s1">    # if no exception, the "something()" gets evaluated,</span>
<span class="s1">    # but the return will not be executed due to the return in the</span>
<span class="s1">    # finally block below.</span>
<span class="s1">finally:</span>
<span class="s1">    # this block will execute no matter what, even if no exception,</span>
<span class="s1">    # after "something" is eval'</span><span class="n">d</span><span class="w"> </span><span class="n">but</span><span class="w"> </span><span class="n">before</span><span class="w"> </span><span class="n">that</span><span class="w"> </span><span class="n">value</span><span class="w"> </span><span class="k">is</span><span class="w"> </span><span class="n">returned</span>
<span class="w">    </span><span class="err">#</span><span class="w"> </span><span class="n">but</span><span class="w"> </span><span class="n">even</span><span class="w"> </span><span class="k">if</span><span class="w"> </span><span class="n">there</span><span class="w"> </span><span class="k">is</span><span class="w"> </span><span class="n">an</span><span class="w"> </span><span class="n">exception</span><span class="o">.</span>
<span class="w">    </span><span class="err">#</span><span class="w"> </span><span class="n">a</span><span class="w"> </span><span class="k">return</span><span class="w"> </span><span class="n">here</span><span class="w"> </span><span class="n">will</span><span class="w"> </span><span class="n">hijack</span><span class="w"> </span><span class="n">the</span><span class="w"> </span><span class="k">return</span><span class="w"> </span><span class="n">functionality</span><span class="o">.</span><span class="w"> </span><span class="n">e</span><span class="o">.</span><span class="na">g</span><span class="o">.:</span>
<span class="w">    </span><span class="k">return</span><span class="w"> </span><span class="n">True</span><span class="w"> </span><span class="err">#</span><span class="w"> </span><span class="n">hijacks</span><span class="w"> </span><span class="n">the</span><span class="w"> </span><span class="k">return</span><span class="w"> </span><span class="k">in</span><span class="w"> </span><span class="n">the</span><span class="w"> </span><span class="k">else</span><span class="w"> </span><span class="n">clause</span><span class="w"> </span><span class="n">above</span>
</pre></div>

<p>的确，我们 <em>可以</em>
将块中的代码包含<code>else</code>在块中<code>try</code>，如果没有异常，它将在块中运行，但是如果该代码本身引发了我们正在捕获的异常怎么办？将它留在<code>try</code>块中会隐藏该错误。</p>
<p>我们希望尽量减少代码<code>try</code>块中的代码行，以避免捕获我们没有预料到的异常，原则是如果我们的代码失败，我们希望它大声失败。这是一个最佳实践。</p>
<blockquote>
<h3>我的理解是异常不是错误</h3>
</blockquote>
<p>在 Python 中，大多数异常都是错误。</p>
<p>我们可以使用 pydoc 查看异常层次结构。例如，在 Python 2 中：</p>
<div class="code"><pre class="code literal-block">$<span class="w"> </span>python<span class="w"> </span>-m<span class="w"> </span>pydoc<span class="w"> </span>exceptions
</pre></div>

<p>或蟒蛇 3：</p>
<div class="code"><pre class="code literal-block">$<span class="w"> </span>python<span class="w"> </span>-m<span class="w"> </span>pydoc<span class="w"> </span>builtins
</pre></div>

<p>会给我们层次结构。我们可以看到大多数类型的<code>Exception</code>错误，尽管 Python 将其中一些用于结束<code>for</code>循环 (
<code>StopIteration</code>) 之类的事情。这是 Python 3 的层次结构：</p>
<div class="code"><pre class="code literal-block"><span class="n">BaseException</span>
<span class="w">    </span><span class="n">Exception</span>
<span class="w">        </span><span class="n">ArithmeticError</span>
<span class="w">            </span><span class="n">FloatingPointError</span>
<span class="w">            </span><span class="n">OverflowError</span>
<span class="w">            </span><span class="n">ZeroDivisionError</span>
<span class="w">        </span><span class="n">AssertionError</span>
<span class="w">        </span><span class="n">AttributeError</span>
<span class="w">        </span><span class="n">BufferError</span>
<span class="w">        </span><span class="n">EOFError</span>
<span class="w">        </span><span class="n">ImportError</span>
<span class="w">            </span><span class="n">ModuleNotFoundError</span>
<span class="w">        </span><span class="n">LookupError</span>
<span class="w">            </span><span class="n">IndexError</span>
<span class="w">            </span><span class="n">KeyError</span>
<span class="w">        </span><span class="n">MemoryError</span>
<span class="w">        </span><span class="n">NameError</span>
<span class="w">            </span><span class="n">UnboundLocalError</span>
<span class="w">        </span><span class="n">OSError</span>
<span class="w">            </span><span class="n">BlockingIOError</span>
<span class="w">            </span><span class="n">ChildProcessError</span>
<span class="w">            </span><span class="n">ConnectionError</span>
<span class="w">                </span><span class="n">BrokenPipeError</span>
<span class="w">                </span><span class="n">ConnectionAbortedError</span>
<span class="w">                </span><span class="n">ConnectionRefusedError</span>
<span class="w">                </span><span class="n">ConnectionResetError</span>
<span class="w">            </span><span class="n">FileExistsError</span>
<span class="w">            </span><span class="n">FileNotFoundError</span>
<span class="w">            </span><span class="n">InterruptedError</span>
<span class="w">            </span><span class="n">IsADirectoryError</span>
<span class="w">            </span><span class="n">NotADirectoryError</span>
<span class="w">            </span><span class="n">PermissionError</span>
<span class="w">            </span><span class="n">ProcessLookupError</span>
<span class="w">            </span><span class="n">TimeoutError</span>
<span class="w">        </span><span class="n">ReferenceError</span>
<span class="w">        </span><span class="n">RuntimeError</span>
<span class="w">            </span><span class="n">NotImplementedError</span>
<span class="w">            </span><span class="n">RecursionError</span>
<span class="w">        </span><span class="n">StopAsyncIteration</span>
<span class="w">        </span><span class="n">StopIteration</span>
<span class="w">        </span><span class="n">SyntaxError</span>
<span class="w">            </span><span class="n">IndentationError</span>
<span class="w">                </span><span class="n">TabError</span>
<span class="w">        </span><span class="n">SystemError</span>
<span class="w">        </span><span class="n">TypeError</span>
<span class="w">        </span><span class="n">ValueError</span>
<span class="w">            </span><span class="n">UnicodeError</span>
<span class="w">                </span><span class="n">UnicodeDecodeError</span>
<span class="w">                </span><span class="n">UnicodeEncodeError</span>
<span class="w">                </span><span class="n">UnicodeTranslateError</span>
<span class="w">        </span><span class="n">Warning</span>
<span class="w">            </span><span class="n">BytesWarning</span>
<span class="w">            </span><span class="n">DeprecationWarning</span>
<span class="w">            </span><span class="n">FutureWarning</span>
<span class="w">            </span><span class="n">ImportWarning</span>
<span class="w">            </span><span class="n">PendingDeprecationWarning</span>
<span class="w">            </span><span class="n">ResourceWarning</span>
<span class="w">            </span><span class="n">RuntimeWarning</span>
<span class="w">            </span><span class="n">SyntaxWarning</span>
<span class="w">            </span><span class="n">UnicodeWarning</span>
<span class="w">            </span><span class="n">UserWarning</span>
<span class="w">    </span><span class="n">GeneratorExit</span>
<span class="w">    </span><span class="n">KeyboardInterrupt</span>
<span class="w">    </span><span class="n">SystemExit</span>
</pre></div>

<p>一位评论者问道：</p>
<blockquote>
<p>假设你有一个 ping 外部 API 的方法，并且你想在 API 包装器之外的类中处理异常，你是否只是从 e 是异常对象的 except
子句下的方法返回 e？</p>
</blockquote>
<p>不，您不返回异常，只是重新引发它<code>raise</code>以保留堆栈跟踪。</p>
<div class="code"><pre class="code literal-block"><span class="k">try</span><span class="o">:</span>
<span class="w">    </span><span class="n">try_this</span><span class="o">(</span><span class="n">whatever</span><span class="o">)</span>
<span class="n">except</span><span class="w"> </span><span class="n">SomeException</span><span class="w"> </span><span class="k">as</span><span class="w"> </span><span class="n">the_exception</span><span class="o">:</span>
<span class="w">    </span><span class="n">handle</span><span class="o">(</span><span class="n">the_exception</span><span class="o">)</span>
<span class="w">    </span><span class="n">raise</span>
</pre></div>

<p>或者，在 Python 3 中，您可以引发新异常并使用异常链接保留回溯：</p>
<div class="code"><pre class="code literal-block"><span class="k">try</span><span class="o">:</span>
<span class="w">    </span><span class="n">try_this</span><span class="o">(</span><span class="n">whatever</span><span class="o">)</span>
<span class="n">except</span><span class="w"> </span><span class="n">SomeException</span><span class="w"> </span><span class="k">as</span><span class="w"> </span><span class="n">the_exception</span><span class="o">:</span>
<span class="w">    </span><span class="n">handle</span><span class="o">(</span><span class="n">the_exception</span><span class="o">)</span>
<span class="w">    </span><span class="n">raise</span><span class="w"> </span><span class="n">DifferentException</span><span class="w"> </span><span class="n">from</span><span class="w"> </span><span class="n">the_exception</span>
</pre></div>

<p>我在这里详细说明我的回答。</p>
<p><br><br><a href="../is-it-a-good-practice-to-use-try-except-else-in-python/">查看原文</a></p>
    </div>
    <aside class="postpromonav"><nav><ul itemprop="keywords" class="tags">
<li><a class="tag p-category" href="../../categories/exception/" rel="tag">exception</a></li>
            <li><a class="tag p-category" href="../../categories/python/" rel="tag">python</a></li>
            <li><a class="tag p-category" href="../../categories/try-catch/" rel="tag">try-catch</a></li>
        </ul>
<ul class="pager hidden-print">
<li class="previous">
                <a href="../mongod-bao-yuan-mei-you-data-db-wen-jian-jia/" rel="prev" title="Mongod 抱怨没有 /data/db 文件夹">Previous post</a>
            </li>
            <li class="next">
                <a href="../ru-he-zhao-dao-python-zhong-liang-ge-datetime-dui-xiang-zhi-jian-de-shi-jian-chai/" rel="next" title="如何找到 python 中两个 datetime 对象之间的时间差？">Next post</a>
            </li>
        </ul></nav></aside></article>
</div>
        <!--End of body content-->

        <footer id="footer">
            Contents © 2023         Go to StackOverflow Chinese Site  <a href="http://stackoverflow.ink">StackOverflow-ZH</a>  
            
        </footer>
</div>
</div>


            <script src="../../assets/js/all-nocdn.js"></script><!-- fancy dates --><script>
    moment.locale("en");
    fancydates(0, "YYYY-MM-DD HH:mm");
    </script><!-- end fancy dates --><script>
    baguetteBox.run('div#content', {
        ignoreClass: 'islink',
        captions: function(element) {
            return element.getElementsByTagName('img')[0].alt;
    }});
    </script><script src="../../assets/js/search.js"></script>
</body>
</html>
