<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>为什么在 Ruby 中 `rescue Exception =&gt; e` 是一种糟糕的风格？ | StackOverflow Snapshot</title>
<link href="../../assets/css/all-nocdn.css" rel="stylesheet" type="text/css">
<meta name="theme-color" content="#5670d4">
<meta name="generator" content="Nikola (getnikola.com)">
<link rel="canonical" href="https://ohstackoverflow.netlify.app/posts/wei-shi-yao-zai-ruby-zhong-rescue-exception-e-shi-yi-chong-zao-gao-de-feng-ge/">
<!--[if lt IE 9]><script src="../../assets/js/html5.js"></script><![endif]--><meta name="author" content="Arya">
<link rel="prev" href="../ru-he-qiang-zhi-wo-de-net-ying-yong-cheng-xu-yi-guan-li-yuan-shen-fen-yun-xing/" title="如何强制我的 .NET 应用程序以管理员身份运行？" type="text/html">
<link rel="next" href="../css-ying-gai-zong-shi-zai-javascript-zhi-qian-ma/" title="CSS 应该总是在 JavaScript 之前吗？" type="text/html">
<meta property="og:site_name" content="StackOverflow Snapshot">
<meta property="og:title" content="为什么在 Ruby 中 `rescue Exception =&gt; e` 是一种糟糕的风格？">
<meta property="og:url" content="https://ohstackoverflow.netlify.app/posts/wei-shi-yao-zai-ruby-zhong-rescue-exception-e-shi-yi-chong-zao-gao-de-feng-ge/">
<meta property="og:description" content="Ryan Davis 的Ruby QuickRef说（没有解释）：

不要拯救异常。曾经。否则我会刺伤你。

为什么不？什么是正确的做法？

解答
TL;DR
：StandardError改为用于一般异常捕获。当重新引发原始异常时（例如，当救援仅记录异常时），救援Exception可能没问题。

Exception是Ruby 异常层次结构的根，因此当您rescue Exception从 所有内容
">
<meta property="og:type" content="article">
<meta property="article:published_time" content="2023-02-17T08:23:20+08:00">
<meta property="article:tag" content="exception">
<meta property="article:tag" content="ruby">
</head>
<body>
<a href="#content" class="sr-only sr-only-focusable">Skip to main content</a>

<!-- Menubar -->

<nav class="navbar navbar-inverse navbar-static-top"><div class="container">
<!-- This keeps the margins nice -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar" aria-controls="bs-navbar" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="https://ohstackoverflow.netlify.app/">

                <span id="blog-title">StackOverflow Snapshot</span>
            </a>
        </div>
<!-- /.navbar-header -->
        <div class="collapse navbar-collapse" id="bs-navbar" aria-expanded="false">
            <ul class="nav navbar-nav">
<li>
<a href="../../archive.html">Archive</a>
                </li>
<li>
<a href="../../categories/">Tags</a>

                
            </li>
</ul>
<ul class="nav navbar-nav navbar-right">
<div style="display:table;min-height:5rem;min-width:27rem;">
					<div class="input-group" style="display: table-cell;vertical-align: middle;">
						<input id="words" type="text" class="form-control" style="max-width:22rem;" onkeydown="if(event.keyCode==13){btn.click()}"><span class="input-group-btn" style="float:left">
							<button id="btn" class="btn btn-default" type="button" data-toggle="modal" data-target="#myModal">
								<span class="glyphicon glyphicon-search">
							</span></button>
						</span>
					</div>
<!-- /input-group -->
				</div>

				
                
                
                
            </ul>
</div>
<!-- /.navbar-collapse -->
    </div>
<!-- /.container -->
</nav><!-- End of Menubar --><!-- 模态框（Modal） --><div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×
				</button>
				<h4 class="modal-title" id="myModalLabel">
					查找结果
				</h4>
			</div>
			<div class="modal-body">
				<div id="search-count" style="min-height:4rem;">
				查找中，请稍后...
				</div>
				<div id="search-result">
				</div>

				
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">
					关闭
				</button>
			</div>
		</div>
<!-- /.modal-content -->
	</div>
<!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="container" id="content" role="main">
    <div class="body-content">
        <!--Body content-->
        <div class="row">
            
            
<article class="post-text h-entry hentry postpage" itemscope="itemscope" itemtype="http://schema.org/Article"><header><h1 class="p-name entry-title" itemprop="headline name"><a href="." class="u-url">为什么在 Ruby 中 `rescue Exception =&gt; e` 是一种糟糕的风格？</a></h1>

        <div class="metadata">
            <p class="byline author vcard p-author h-card"><span class="byline-name fn p-name" itemprop="author">
                    <a class="u-url" href="../../authors/arya/">Arya</a>
            </span></p>
            <p class="dateline">
            <a href="." rel="bookmark">
            <time class="published dt-published" datetime="2023-02-17T08:23:20+08:00" itemprop="datePublished" title="2023-02-17 08:23">2023-02-17 08:23</time></a>
            </p>
            

        </div>
        

    </header><div class="e-content entry-content" itemprop="articleBody text">
    <p>Ryan Davis 的Ruby QuickRef说（没有解释）：</p>
<blockquote>
<p>不要拯救异常。曾经。否则我会刺伤你。</p>
</blockquote>
<p>为什么不？什么是正确的做法？</p>
<p><br><br></p>
<h2>解答</h2>
<p><strong>TL;DR</strong>
：<code>StandardError</code>改为用于一般异常捕获。当重新引发原始异常时（例如，当救援仅记录异常时），救援<code>Exception</code>可能没问题。</p>
<hr>
<p><code>Exception</code>是Ruby 异常层次结构的根，因此当您<code>rescue Exception</code>从 <em>所有内容</em>
中解救出来时，包括<code>SyntaxError</code>、<code>LoadError</code>和 等子类<code>Interrupt</code>。</p>
<p>拯救<code>Interrupt</code>防止用户使用<code>CTRL``C</code>退出程序。</p>
<p>救援<code>SignalException</code>会阻止程序正确响应信号。它将无法杀死，除非<code>kill -9</code>.</p>
<p>救援<code>SyntaxError</code>意味着<code>eval</code>失败的 s 会默默地这样做。</p>
<p>所有这些都可以通过运行这个程序来显示，并尝试<code>CTRL``C</code>or<code>kill</code>它：</p>
<div class="code"><pre class="code literal-block"><span class="k">loop</span><span class="w"> </span><span class="k">do</span>
<span class="w">  </span><span class="nv">begin</span>
<span class="w">    </span><span class="nv">sleep</span><span class="w"> </span><span class="mi">1</span>
<span class="w">    </span><span class="nv">eval</span><span class="w"> </span><span class="s2">"djsakru3924r9eiuorwju3498 += 5u84fior8u8t4ruyf8ihiure"</span>
<span class="w">  </span><span class="nv">rescue</span><span class="w"> </span><span class="nv">Exception</span>
<span class="w">    </span><span class="nv">puts</span><span class="w"> </span><span class="s2">"I refuse to fail or be stopped!"</span>
<span class="w">  </span><span class="k">end</span>
<span class="k">end</span>
</pre></div>

<p>从中拯救<code>Exception</code>甚至不是默认设置。正在做</p>
<div class="code"><pre class="code literal-block"><span class="nv">begin</span>
<span class="w">  </span>#<span class="w"> </span><span class="nv">iceberg</span><span class="o">!</span>
<span class="nv">rescue</span>
<span class="w">  </span>#<span class="w"> </span><span class="nv">lifeboats</span>
<span class="k">end</span>
</pre></div>

<p>不从中拯救<code>Exception</code>，从中拯救<code>StandardError</code>。您通常应该指定比默认值更具体的内容<code>StandardError</code>，但是从中拯救会<code>Exception</code>
<em>扩大</em> 而不是缩小范围，并且可能会产生灾难性的结果并使查找错误变得极其困难。</p>
<hr>
<p>如果你确实想从中拯救<code>StandardError</code>并且需要一个带有异常的变量，你可以使用这种形式：</p>
<div class="code"><pre class="code literal-block"><span class="nv">begin</span>
<span class="w">  </span>#<span class="w"> </span><span class="nv">iceberg</span><span class="o">!</span>
<span class="nv">rescue</span><span class="w"> </span><span class="o">=&gt;</span><span class="w"> </span><span class="nv">e</span>
<span class="w">  </span>#<span class="w"> </span><span class="nv">lifeboats</span>
<span class="k">end</span>
</pre></div>

<p>这相当于：</p>
<div class="code"><pre class="code literal-block"><span class="nv">begin</span>
<span class="w">  </span>#<span class="w"> </span><span class="nv">iceberg</span><span class="o">!</span>
<span class="nv">rescue</span><span class="w"> </span><span class="nv">StandardError</span><span class="w"> </span><span class="o">=&gt;</span><span class="w"> </span><span class="nv">e</span>
<span class="w">  </span>#<span class="w"> </span><span class="nv">lifeboats</span>
<span class="k">end</span>
</pre></div>

<hr>
<p>为数不多的可以理智挽救的常见情况之一<code>Exception</code>是出于日志记录/报告的目的，在这种情况下，您应该立即重新引发异常：</p>
<div class="code"><pre class="code literal-block"><span class="nv">begin</span>
<span class="w">  </span>#<span class="w"> </span><span class="nv">iceberg</span>?
<span class="nv">rescue</span><span class="w"> </span><span class="nv">Exception</span><span class="w"> </span><span class="o">=&gt;</span><span class="w"> </span><span class="nv">e</span>
<span class="w">  </span>#<span class="w"> </span><span class="k">do</span><span class="w"> </span><span class="nv">some</span><span class="w"> </span><span class="nv">logging</span>
<span class="w">  </span><span class="nv">raise</span><span class="w"> </span>#<span class="w"> </span><span class="nv">not</span><span class="w"> </span><span class="nv">enough</span><span class="w"> </span><span class="nv">lifeboats</span><span class="w"> </span><span class="c1">;)</span>
<span class="k">end</span>
</pre></div>

<p><br></p>
<h3>更多建议</h3>
<p><em>真正的</em> 规则是：不要丢弃异常。您引用的作者的客观性值得怀疑，正如其结尾的事实所证明的那样</p>
<blockquote>
<p>否则我会刺伤你</p>
</blockquote>
<p>当然，请注意信号（默认情况下）会抛出异常，并且通常长时间运行的进程会通过信号终止，因此捕获异常而不终止信号异常将使您的程序很难停止。所以不要这样做：</p>
<div class="code"><table class="codetable">
<tr>
<td class="linenos linenodiv"><a href="#-1"><code data-line-number=" 1"></code></a></td>
<td class="code"><code><span class="ch">#! /usr/bin/ruby</span>
</code></td>
</tr>
<tr>
<td class="linenos linenodiv"><a href="#-2"><code data-line-number=" 2"></code></a></td>
<td class="code"><code>
</code></td>
</tr>
<tr>
<td class="linenos linenodiv"><a href="#-3"><code data-line-number=" 3"></code></a></td>
<td class="code"><code><span class="k">while</span><span class="w"> </span><span class="kp">true</span><span class="w"> </span><span class="k">do</span>
</code></td>
</tr>
<tr>
<td class="linenos linenodiv"><a href="#-4"><code data-line-number=" 4"></code></a></td>
<td class="code"><code><span class="w">  </span><span class="k">begin</span>
</code></td>
</tr>
<tr>
<td class="linenos linenodiv"><a href="#-5"><code data-line-number=" 5"></code></a></td>
<td class="code"><code><span class="w">    </span><span class="n">line</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="no">STDIN</span><span class="o">.</span><span class="n">gets</span>
</code></td>
</tr>
<tr>
<td class="linenos linenodiv"><a href="#-6"><code data-line-number=" 6"></code></a></td>
<td class="code"><code><span class="w">    </span><span class="c1"># heavy processing</span>
</code></td>
</tr>
<tr>
<td class="linenos linenodiv"><a href="#-7"><code data-line-number=" 7"></code></a></td>
<td class="code"><code><span class="w">  </span><span class="k">rescue</span><span class="w"> </span><span class="no">Exception</span><span class="w"> </span><span class="o">=&gt;</span><span class="w"> </span><span class="n">e</span>
</code></td>
</tr>
<tr>
<td class="linenos linenodiv"><a href="#-8"><code data-line-number=" 8"></code></a></td>
<td class="code"><code><span class="w">    </span><span class="nb">puts</span><span class="w"> </span><span class="s2">"caught exception </span><span class="si">#{</span><span class="n">e</span><span class="si">}</span><span class="s2">! ohnoes!"</span>
</code></td>
</tr>
<tr>
<td class="linenos linenodiv"><a href="#-9"><code data-line-number=" 9"></code></a></td>
<td class="code"><code><span class="w">  </span><span class="k">end</span>
</code></td>
</tr>
<tr>
<td class="linenos linenodiv"><a href="#-10"><code data-line-number="10"></code></a></td>
<td class="code"><code><span class="k">end</span>
</code></td>
</tr>
</table></div>
<p>不，真的，不要这样做。甚至不要运行它来查看它是否有效。</p>
<p>但是，假设您有一个线程服务器并且您不希望所有异常：</p>
<ol>
<li>被忽略（默认）</li>
<li>停止服务器（如果你说会发生<code>thread.abort_on_exception = true</code>）。</li>
</ol>
<p>那么这在您的连接处理线程中是完全可以接受的：</p>
<div class="code"><pre class="code literal-block"><span class="nv">begin</span>
<span class="w">  </span>#<span class="w"> </span><span class="k">do</span><span class="w"> </span><span class="nv">stuff</span>
<span class="nv">rescue</span><span class="w"> </span><span class="nv">Exception</span><span class="w"> </span><span class="o">=&gt;</span><span class="w"> </span><span class="nv">e</span>
<span class="w">  </span><span class="nv">myLogger</span>.<span class="nv">error</span><span class="ss">(</span><span class="s2">"uncaught #{e} exception while handling connection: #{e.message}"</span><span class="ss">)</span>
<span class="w">    </span><span class="nv">myLogger</span>.<span class="nv">error</span><span class="ss">(</span><span class="s2">"Stack trace: #{backtrace.map {|l| "</span><span class="w">  </span>#{<span class="nv">l</span>}\<span class="nv">n</span><span class="s2">"}.join}"</span><span class="ss">)</span>
<span class="k">end</span>
</pre></div>

<p>以上是 Ruby 默认异常处理程序的变体，其优点是它不会终止您的程序。Rails 在其请求处理程序中执行此操作。</p>
<p>在主线程中引发信号异常。后台线程不会得到它们，所以试图在那里捕获它们是没有意义的。</p>
<p>这在生产环境中特别有用，因为您不 <em>希望</em>
您的程序在出现问题时简单地停止。然后，您可以在日志中获取堆栈转储并添加到您的代码中，以更优雅的方式在调用链的下游进一步处理特定异常。</p>
<p>另请注意，还有另一个 Ruby 惯用语具有大致相同的效果：</p>
<div class="code"><pre class="code literal-block"><span class="nv">a</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="nv">do_something</span><span class="w"> </span><span class="nv">rescue</span><span class="w"> </span><span class="s2">"something else"</span>
</pre></div>

<p>在这一行中，如果<code>do_something</code>引发异常，它会被 Ruby 捕获、丢弃并<code>a</code>赋值<code>"something else"</code>。</p>
<p>一般来说，不要那样做，除非在你 <em>知道</em> 你不需要担心的特殊情况下。一个例子：</p>
<div class="code"><pre class="code literal-block">debugger rescue nil
</pre></div>

<p>该<code>debugger</code>函数是在代码中设置断点的一种相当不错的方法，但如果在调试器和 Rails
之外运行，它会引发异常。现在理论上你不应该在你的程序中留下调试代码（pff！没有人那样做！）但你可能出于某种原因希望将它保留一段时间，但不要持续运行你的调试器。</p>
<p>笔记：</p>
<ol>
<li>
<p>如果你运行了别人的程序来捕获信号异常并忽略它们，（比如上面的代码）那么：</p>
<ul>
<li>在 Linux 中，在 shell 中键入<code>pgrep ruby</code>或<code>ps | grep ruby</code>，查找您有问题的程序的 PID，然后运行<code>kill -9 &lt;PID&gt;</code>​​。</li>
<li>在 Windows 中，使用任务管理器 ( <code>CTRL</code>- <code>SHIFT</code>- <code>ESC</code>)，转到“进程”选项卡，找到您的进程，右键单击它并选择“结束进程”。</li>
<li>
<p>如果您正在使用其他人的程序，无论出于何种原因，这些程序都充满了这些忽略异常块，那么将它放在主线的顶部是一种可能的逃避：</p>
<p>%W/INT QUIT TERM/.each { |sig| trap sig,"SYSTEM_DEFAULT" }</p>
</li>
</ul>
</li>
</ol>
<p><em>这会导致程序通过立即终止、绕过异常处理程序而不进行清理</em> 来响应正常的终止信号。所以它可能会导致数据丢失或类似情况。当心！</p>
<ol>
<li>如果您需要这样做：<div class="code"><pre class="code literal-block">begin
</pre></div>

<p>do_something
rescue Exception =&gt; e
  critical_cleanup
  raise
end</p>
</li>
</ol>
<p>你实际上可以这样做：</p>
<div class="code"><pre class="code literal-block"><span class="w">    </span><span class="nv">begin</span>
<span class="w">  </span><span class="nv">do_something</span>
<span class="nv">ensure</span>
<span class="w">  </span><span class="nv">critical_cleanup</span>
<span class="k">end</span>
</pre></div>

<p>在第二种情况下，<code>critical cleanup</code>无论是否抛出异常，每次都会被调用。</p>
<p><br><br><a href="../why-is-it-bad-style-to-rescue-exception-e-in-ruby/">查看原文</a></p>
    </div>
    <aside class="postpromonav"><nav><ul itemprop="keywords" class="tags">
<li><a class="tag p-category" href="../../categories/exception/" rel="tag">exception</a></li>
            <li><a class="tag p-category" href="../../categories/ruby/" rel="tag">ruby</a></li>
        </ul>
<ul class="pager hidden-print">
<li class="previous">
                <a href="../ru-he-qiang-zhi-wo-de-net-ying-yong-cheng-xu-yi-guan-li-yuan-shen-fen-yun-xing/" rel="prev" title="如何强制我的 .NET 应用程序以管理员身份运行？">Previous post</a>
            </li>
            <li class="next">
                <a href="../css-ying-gai-zong-shi-zai-javascript-zhi-qian-ma/" rel="next" title="CSS 应该总是在 JavaScript 之前吗？">Next post</a>
            </li>
        </ul></nav></aside></article>
</div>
        <!--End of body content-->

        <footer id="footer">
            Contents © 2023         Go to StackOverflow Chinese Site  <a href="http://stackoverflow.ink">StackOverflow-ZH</a>  
            
        </footer>
</div>
</div>


            <script src="../../assets/js/all-nocdn.js"></script><!-- fancy dates --><script>
    moment.locale("en");
    fancydates(0, "YYYY-MM-DD HH:mm");
    </script><!-- end fancy dates --><script>
    baguetteBox.run('div#content', {
        ignoreClass: 'islink',
        captions: function(element) {
            return element.getElementsByTagName('img')[0].alt;
    }});
    </script><script src="../../assets/js/search.js"></script>
</body>
</html>
