<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>What is the difference between `throw new Error` and `throw someObject`? | StackOverflow Snapshot</title>
<link href="../../assets/css/all-nocdn.css" rel="stylesheet" type="text/css">
<meta name="theme-color" content="#5670d4">
<meta name="generator" content="Nikola (getnikola.com)">
<link rel="canonical" href="https://ohstackoverflow.netlify.app/posts/what-is-the-difference-between-throw-new-error-and-throw-someobject/">
<!--[if lt IE 9]><script src="../../assets/js/html5.js"></script><![endif]--><meta name="author" content="Arya">
<link rel="prev" href="../does-typescript-support-the-operator-and-what-s-it-called/" title="Does Typescript support the ?. operator? (And, what's it called?)" type="text/html">
<link rel="next" href="../how-can-i-pivot-a-dataframe/" title="How can I pivot a dataframe?" type="text/html">
<meta property="og:site_name" content="StackOverflow Snapshot">
<meta property="og:title" content="What is the difference between `throw new Error` and `throw someObject">
<meta property="og:url" content="https://ohstackoverflow.netlify.app/posts/what-is-the-difference-between-throw-new-error-and-throw-someobject/">
<meta property="og:description" content="I want to write a common error handler which will catch custom errors thrown
on purpose at any instance of the code.
When I did throw new Error('sample') like in the following code
try {
    throw new">
<meta property="og:type" content="article">
<meta property="article:published_time" content="2023-02-18T02:23:58+08:00">
<meta property="article:tag" content="error-handling">
<meta property="article:tag" content="exception">
<meta property="article:tag" content="javascript">
<meta property="article:tag" content="object">
<meta property="article:tag" content="throw">
</head>
<body>
<a href="#content" class="sr-only sr-only-focusable">Skip to main content</a>

<!-- Menubar -->

<nav class="navbar navbar-inverse navbar-static-top"><div class="container">
<!-- This keeps the margins nice -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar" aria-controls="bs-navbar" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="https://ohstackoverflow.netlify.app/">

                <span id="blog-title">StackOverflow Snapshot</span>
            </a>
        </div>
<!-- /.navbar-header -->
        <div class="collapse navbar-collapse" id="bs-navbar" aria-expanded="false">
            <ul class="nav navbar-nav">
<li>
<a href="../../archive.html">Archive</a>
                </li>
<li>
<a href="../../categories/">Tags</a>

                
            </li>
</ul>
<ul class="nav navbar-nav navbar-right">
<div style="display:table;min-height:5rem;min-width:27rem;">
					<div class="input-group" style="display: table-cell;vertical-align: middle;">
						<input id="words" type="text" class="form-control" style="max-width:22rem;" onkeydown="if(event.keyCode==13){btn.click()}"><span class="input-group-btn" style="float:left">
							<button id="btn" class="btn btn-default" type="button" data-toggle="modal" data-target="#myModal">
								<span class="glyphicon glyphicon-search">
							</span></button>
						</span>
					</div>
<!-- /input-group -->
				</div>

				
                
                
                
            </ul>
</div>
<!-- /.navbar-collapse -->
    </div>
<!-- /.container -->
</nav><!-- End of Menubar --><!-- 模态框（Modal） --><div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×
				</button>
				<h4 class="modal-title" id="myModalLabel">
					查找结果
				</h4>
			</div>
			<div class="modal-body">
				<div id="search-count" style="min-height:4rem;">
				查找中，请稍后...
				</div>
				<div id="search-result">
				</div>

				
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">
					关闭
				</button>
			</div>
		</div>
<!-- /.modal-content -->
	</div>
<!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="container" id="content" role="main">
    <div class="body-content">
        <!--Body content-->
        <div class="row">
            
            
<article class="post-text h-entry hentry postpage" itemscope="itemscope" itemtype="http://schema.org/Article"><header><h1 class="p-name entry-title" itemprop="headline name"><a href="." class="u-url">What is the difference between `throw new Error` and `throw someObject`?</a></h1>

        <div class="metadata">
            <p class="byline author vcard p-author h-card"><span class="byline-name fn p-name" itemprop="author">
                    <a class="u-url" href="../../authors/arya/">Arya</a>
            </span></p>
            <p class="dateline">
            <a href="." rel="bookmark">
            <time class="published dt-published" datetime="2023-02-18T02:23:58+08:00" itemprop="datePublished" title="2023-02-18 02:23">2023-02-18 02:23</time></a>
            </p>
            

        </div>
        

    </header><div class="e-content entry-content" itemprop="articleBody text">
    <p>I want to write a common error handler which will catch custom errors thrown
on purpose at any instance of the code.</p>
<p>When I did <code>throw new Error('sample')</code> like in the following code</p>
<div class="code"><pre class="code literal-block">try {
    throw new Error({'hehe':'haha'});
    // throw new Error('hehe');
} catch(e) {
    alert(e);
    console.log(e);
}
</pre></div>

<p>Log shows in Firefox as <code>Error: [object Object]</code> and I couldn’t parse the
object.</p>
<p>For the second <code>throw</code> the log shows as: <code>Error: hehe</code></p>
<p>Whereas when I did</p>
<div class="code"><pre class="code literal-block">try {
    throw ({'hehe':'haha'});
} catch(e) {
    alert(e);
    console.log(e);
}
</pre></div>

<p>the console showed as: <code>Object { hehe="haha"}</code> in which I was able to access
the error properties.</p>
<p><strong>What is the difference?</strong></p>
<p>Is the difference as seen in the code? Like string will be just passed as
string and object as objects but the syntax will be different?</p>
<p>I haven’t explored throwing error object… I had done only throwing strings.</p>
<p>Is there any other way than the above two mentioned methods?</p>
<p><br><br></p>
<h2>Answer</h2>
<p>The difference between 'throw new Error' and 'throw someObject' in javascript
is that throw new Error wraps the error passed to it in the following format −</p>
<blockquote>
<p>{ name: 'Error', message: 'String you pass in the constructor' }</p>
</blockquote>
<p>The throw someObject will throw the object as is and will not allow any
further code execution from the try block, ie same as throw new Error.</p>
<p>Here is a good explanation about The Error object and throwing your own errors</p>
<p><strong>The Error Object</strong></p>
<p>Just what we can extract from it in an event of an error? The Error object in
all browsers support the following two properties:</p>
<ul>
<li>
<p>name: The name of the error, or more specifically, the name of the constructor function the error belongs to.</p>
</li>
<li>
<p>message: A description of the error, with this description varying depending on the browser.</p>
</li>
</ul>
<p>Six possible values can be returned by the name property, which as mentioned
correspond to the names of the error's constructors. They are:</p>
<div class="code"><pre class="code literal-block"><span class="n">Error</span> <span class="n">Name</span>          <span class="n">Description</span>

<span class="n">EvalError</span>           <span class="n">An</span> <span class="n">error</span> <span class="nb">in</span> <span class="n">the</span> <span class="n">eval</span>() <span class="n">function</span> <span class="k">has</span> <span class="n">occurred</span>.

<span class="n">RangeError</span>          <span class="n">Out</span> <span class="nb">of</span> <span class="nb">range</span> <span class="n">number</span> <span class="nb">value</span> <span class="k">has</span> <span class="n">occurred</span>.

<span class="n">ReferenceError</span>      <span class="n">An</span> <span class="nb">illegal</span> <span class="n">reference</span> <span class="k">has</span> <span class="n">occurred</span>.

<span class="n">SyntaxError</span>         <span class="n">A</span> <span class="n">syntax</span> <span class="n">error</span> <span class="n">within</span> <span class="nb">code</span> <span class="n">inside</span> <span class="n">the</span> <span class="n">eval</span>() <span class="n">function</span> <span class="k">has</span> <span class="n">occurred</span>.
                    <span class="n">All</span> <span class="n">other</span> <span class="n">syntax</span> <span class="n">errors</span> <span class="n">are</span> <span class="nb">not</span> <span class="n">caught</span> <span class="n">by</span> <span class="k">try</span><span class="o">/</span><span class="n">catch</span><span class="o">/</span><span class="n">finally</span>, <span class="o">and</span> <span class="n">will</span>
                    <span class="n">trigger</span> <span class="n">the</span> <span class="k">default</span> <span class="n">browser</span> <span class="n">error</span> <span class="nb">message</span> <span class="n">associated</span> <span class="k">with</span> <span class="n">the</span> <span class="n">error</span>. 
                    <span class="n">To</span> <span class="n">catch</span> <span class="n">actual</span> <span class="n">syntax</span> <span class="n">errors</span>, <span class="n">you</span> <span class="n">may</span> <span class="k">use</span> <span class="n">the</span> <span class="n">onerror</span> <span class="n">event</span>.

<span class="n">TypeError</span>           <span class="n">An</span> <span class="n">error</span> <span class="nb">in</span> <span class="n">the</span> <span class="nb">expected</span> <span class="nb">variable</span> <span class="nb">type</span> <span class="k">has</span> <span class="n">occurred</span>.

<span class="n">URIError</span>            <span class="n">An</span> <span class="n">error</span> <span class="k">when</span> <span class="nb">encoding</span> <span class="o">or</span> <span class="n">decoding</span> <span class="n">the</span> <span class="n">URI</span> <span class="k">has</span> <span class="n">occurred</span> 
                   (<span class="n">ie:</span> <span class="k">when</span> <span class="n">calling</span> <span class="n">encodeURI</span>()).
</pre></div>

<p><strong>Throwing your own errors (exceptions)</strong></p>
<p>Instead of waiting for one of the 6 types of errors to occur before control is
automatically transferred from the try block to the catch block, you can also
explicitly throw your own exceptions to force that to happen on demand. This
is great for creating your own definitions of what an error is and when
control should be transferred to catch.</p>
<p><br></p>
<h3>Suggest</h3>
<h3>throw "I'm Evil"</h3>
<p><code>throw</code> will <strong>terminate</strong> the further execution &amp; expose message string on
<strong>catch</strong> the error.</p>
<div class="code"><pre class="code literal-block">try {
  throw "I'm Evil"
  console.log("You'll never reach to me", 123465)
} catch (e) {
  console.log(e); // I'm Evil
}
</pre></div>

<p>Console after <strong>throw</strong> will never be reached cause of termination.</p>
<hr>
<h3>throw new Error("I'm Evil")</h3>
<p><code>throw new Error</code> exposes an error event with two params <strong>name</strong> &amp;
<strong>message</strong>. It also terminate further execution</p>
<div class="code"><pre class="code literal-block">try {
  throw new Error("I'm Evil")
  console.log("You'll never reach to me", 123465)
} catch (e) {
  console.log(e.name, e.message); // Error I'm Evil
}
</pre></div>

<h3>throw Error("I'm Evil")</h3>
<p>And just for completeness, this works also, though is not technically the
correct way to do it -</p>
<div class="code"><pre class="code literal-block">try {
  throw Error("I'm Evil")
  console.log("You'll never reach to me", 123465)
} catch (e) {
  console.log(e.name, e.message); // Error I'm Evil
}

console.log(typeof(new Error("hello"))) // object
console.log(typeof(Error)) // function
</pre></div>
    </div>
    <aside class="postpromonav"><nav><ul itemprop="keywords" class="tags">
<li><a class="tag p-category" href="../../categories/error-handling/" rel="tag">error-handling</a></li>
            <li><a class="tag p-category" href="../../categories/exception/" rel="tag">exception</a></li>
            <li><a class="tag p-category" href="../../categories/javascript/" rel="tag">javascript</a></li>
            <li><a class="tag p-category" href="../../categories/object/" rel="tag">object</a></li>
            <li><a class="tag p-category" href="../../categories/throw/" rel="tag">throw</a></li>
        </ul>
<ul class="pager hidden-print">
<li class="previous">
                <a href="../does-typescript-support-the-operator-and-what-s-it-called/" rel="prev" title="Does Typescript support the ?. operator? (And, what's it called?)">Previous post</a>
            </li>
            <li class="next">
                <a href="../how-can-i-pivot-a-dataframe/" rel="next" title="How can I pivot a dataframe?">Next post</a>
            </li>
        </ul></nav></aside></article>
</div>
        <!--End of body content-->

        <footer id="footer">
            Contents © 2023         Go to StackOverflow Chinese Site  <a href="http://stackoverflow.ink">StackOverflow-ZH</a>  
            
        </footer>
</div>
</div>


            <script src="../../assets/js/all-nocdn.js"></script><!-- fancy dates --><script>
    moment.locale("en");
    fancydates(0, "YYYY-MM-DD HH:mm");
    </script><!-- end fancy dates --><script>
    baguetteBox.run('div#content', {
        ignoreClass: 'islink',
        captions: function(element) {
            return element.getElementsByTagName('img')[0].alt;
    }});
    </script><script src="../../assets/js/search.js"></script>
</body>
</html>
