<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>`throw new Error` 和 `throw someObject` 有什么区别？ | StackOverflow Snapshot</title>
<link href="../../assets/css/all-nocdn.css" rel="stylesheet" type="text/css">
<meta name="theme-color" content="#5670d4">
<meta name="generator" content="Nikola (getnikola.com)">
<link rel="canonical" href="https://ohstackoverflow.netlify.app/posts/throw-new-error-he-throw-someobject-you-shi-yao-qu-bie/">
<!--[if lt IE 9]><script src="../../assets/js/html5.js"></script><![endif]--><meta name="author" content="Arya">
<link rel="prev" href="../typescript-shi-fou-zhi-chi-cao-zuo-yuan-huan-you-ta-jiao-shi-yao/" title="Typescript 是否支持 ?. 操作员？（还有，它叫什么？）" type="text/html">
<link rel="next" href="../ru-he-xuan-zhuan-shu-ju-kuang/" title="如何旋转数据框？" type="text/html">
<meta property="og:site_name" content="StackOverflow Snapshot">
<meta property="og:title" content="`throw new Error` 和 `throw someObject` 有什么区别？">
<meta property="og:url" content="https://ohstackoverflow.netlify.app/posts/throw-new-error-he-throw-someobject-you-shi-yao-qu-bie/">
<meta property="og:description" content="我想编写一个通用的错误处理程序，它将捕获在代码的任何实例中故意抛出的自定义错误。
当我throw new Error('sample')喜欢下面的代码时
try {
    throw new Error({'hehe':'haha'});
    // throw new Error('hehe');
} catch(e) {
    alert(e);
    console.log(e);
">
<meta property="og:type" content="article">
<meta property="article:published_time" content="2023-02-18T02:24:19+08:00">
<meta property="article:tag" content="error-handling">
<meta property="article:tag" content="exception">
<meta property="article:tag" content="javascript">
<meta property="article:tag" content="object">
<meta property="article:tag" content="throw">
</head>
<body>
<a href="#content" class="sr-only sr-only-focusable">Skip to main content</a>

<!-- Menubar -->

<nav class="navbar navbar-inverse navbar-static-top"><div class="container">
<!-- This keeps the margins nice -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar" aria-controls="bs-navbar" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="https://ohstackoverflow.netlify.app/">

                <span id="blog-title">StackOverflow Snapshot</span>
            </a>
        </div>
<!-- /.navbar-header -->
        <div class="collapse navbar-collapse" id="bs-navbar" aria-expanded="false">
            <ul class="nav navbar-nav">
<li>
<a href="../../archive.html">Archive</a>
                </li>
<li>
<a href="../../categories/">Tags</a>

                
            </li>
</ul>
<ul class="nav navbar-nav navbar-right">
<div style="display:table;min-height:5rem;min-width:27rem;">
					<div class="input-group" style="display: table-cell;vertical-align: middle;">
						<input id="words" type="text" class="form-control" style="max-width:22rem;" onkeydown="if(event.keyCode==13){btn.click()}"><span class="input-group-btn" style="float:left">
							<button id="btn" class="btn btn-default" type="button" data-toggle="modal" data-target="#myModal">
								<span class="glyphicon glyphicon-search">
							</span></button>
						</span>
					</div>
<!-- /input-group -->
				</div>

				
                
                
                
            </ul>
</div>
<!-- /.navbar-collapse -->
    </div>
<!-- /.container -->
</nav><!-- End of Menubar --><!-- 模态框（Modal） --><div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×
				</button>
				<h4 class="modal-title" id="myModalLabel">
					查找结果
				</h4>
			</div>
			<div class="modal-body">
				<div id="search-count" style="min-height:4rem;">
				查找中，请稍后...
				</div>
				<div id="search-result">
				</div>

				
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">
					关闭
				</button>
			</div>
		</div>
<!-- /.modal-content -->
	</div>
<!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="container" id="content" role="main">
    <div class="body-content">
        <!--Body content-->
        <div class="row">
            
            
<article class="post-text h-entry hentry postpage" itemscope="itemscope" itemtype="http://schema.org/Article"><header><h1 class="p-name entry-title" itemprop="headline name"><a href="." class="u-url">`throw new Error` 和 `throw someObject` 有什么区别？</a></h1>

        <div class="metadata">
            <p class="byline author vcard p-author h-card"><span class="byline-name fn p-name" itemprop="author">
                    <a class="u-url" href="../../authors/arya/">Arya</a>
            </span></p>
            <p class="dateline">
            <a href="." rel="bookmark">
            <time class="published dt-published" datetime="2023-02-18T02:24:19+08:00" itemprop="datePublished" title="2023-02-18 02:24">2023-02-18 02:24</time></a>
            </p>
            

        </div>
        

    </header><div class="e-content entry-content" itemprop="articleBody text">
    <p>我想编写一个通用的错误处理程序，它将捕获在代码的任何实例中故意抛出的自定义错误。</p>
<p>当我<code>throw new Error('sample')</code>喜欢下面的代码时</p>
<div class="code"><pre class="code literal-block">try {
    throw new Error({'hehe':'haha'});
    // throw new Error('hehe');
} catch(e) {
    alert(e);
    console.log(e);
}
</pre></div>

<p>日志在 Firefox 中显示为<code>Error: [object Object]</code>，我无法解析该对象。</p>
<p>第二个<code>throw</code>日志显示为：<code>Error: hehe</code></p>
<p>而当我这样做的时候</p>
<div class="code"><pre class="code literal-block">try {
    throw ({'hehe':'haha'});
} catch(e) {
    alert(e);
    console.log(e);
}
</pre></div>

<p>控制台显示为：<code>Object { hehe="haha"}</code>我可以在其中访问错误属性。</p>
<p><strong>有什么不同？</strong></p>
<p>代码中是否存在差异？就像字符串将作为字符串和对象作为对象传递一样，但语法会有所不同吗？</p>
<p>我还没有探索过抛出错误对象……我只做过抛出字符串。</p>
<p>除了上述两种方法，还有其他方法吗？</p>
<p><br><br></p>
<h2>解答</h2>
<p>javascript 中“throw new Error”和“throw someObject”的区别在于 throw new Error
以以下格式包装传递给它的错误 -</p>
<blockquote>
<p>{ name: 'Error', message: 'String you pass in the constructor' }</p>
</blockquote>
<p>throw someObject 将按原样抛出对象，并且不允许从 try 块中执行任何进一步的代码，即与 throw new Error 相同。</p>
<p>这是关于The Error 对象和抛出你自己的错误的一个很好的解释</p>
<p><strong>错误对象</strong></p>
<p>如果发生错误，我们可以从中提取什么？所有浏览器中的 Error 对象都支持以下两个属性：</p>
<ul>
<li>
<p>name：错误的名称，或者更具体地说，错误所属的构造函数的名称。</p>
</li>
<li>
<p>消息：错误的描述，此描述因浏览器而异。</p>
</li>
</ul>
<p>name 属性可以返回六个可能的值，如前所述，这些值对应于错误构造函数的名称。他们是：</p>
<div class="code"><pre class="code literal-block"><span class="n">Error</span> <span class="n">Name</span>          <span class="n">Description</span>

<span class="n">EvalError</span>           <span class="n">An</span> <span class="n">error</span> <span class="nb">in</span> <span class="n">the</span> <span class="n">eval</span>() <span class="n">function</span> <span class="k">has</span> <span class="n">occurred</span>.

<span class="n">RangeError</span>          <span class="n">Out</span> <span class="nb">of</span> <span class="nb">range</span> <span class="n">number</span> <span class="nb">value</span> <span class="k">has</span> <span class="n">occurred</span>.

<span class="n">ReferenceError</span>      <span class="n">An</span> <span class="nb">illegal</span> <span class="n">reference</span> <span class="k">has</span> <span class="n">occurred</span>.

<span class="n">SyntaxError</span>         <span class="n">A</span> <span class="n">syntax</span> <span class="n">error</span> <span class="n">within</span> <span class="nb">code</span> <span class="n">inside</span> <span class="n">the</span> <span class="n">eval</span>() <span class="n">function</span> <span class="k">has</span> <span class="n">occurred</span>.
                    <span class="n">All</span> <span class="n">other</span> <span class="n">syntax</span> <span class="n">errors</span> <span class="n">are</span> <span class="nb">not</span> <span class="n">caught</span> <span class="n">by</span> <span class="k">try</span><span class="o">/</span><span class="n">catch</span><span class="o">/</span><span class="n">finally</span>, <span class="o">and</span> <span class="n">will</span>
                    <span class="n">trigger</span> <span class="n">the</span> <span class="k">default</span> <span class="n">browser</span> <span class="n">error</span> <span class="nb">message</span> <span class="n">associated</span> <span class="k">with</span> <span class="n">the</span> <span class="n">error</span>. 
                    <span class="n">To</span> <span class="n">catch</span> <span class="n">actual</span> <span class="n">syntax</span> <span class="n">errors</span>, <span class="n">you</span> <span class="n">may</span> <span class="k">use</span> <span class="n">the</span> <span class="n">onerror</span> <span class="n">event</span>.

<span class="n">TypeError</span>           <span class="n">An</span> <span class="n">error</span> <span class="nb">in</span> <span class="n">the</span> <span class="nb">expected</span> <span class="nb">variable</span> <span class="nb">type</span> <span class="k">has</span> <span class="n">occurred</span>.

<span class="n">URIError</span>            <span class="n">An</span> <span class="n">error</span> <span class="k">when</span> <span class="nb">encoding</span> <span class="o">or</span> <span class="n">decoding</span> <span class="n">the</span> <span class="n">URI</span> <span class="k">has</span> <span class="n">occurred</span> 
                   (<span class="n">ie:</span> <span class="k">when</span> <span class="n">calling</span> <span class="n">encodeURI</span>()).
</pre></div>

<p><strong>抛出你自己的错误（例外）</strong></p>
<p>在控制自动从 try 块转移到 catch 块之前，您不必等待 6
种类型的错误中的一种发生，您还可以显式抛出您自己的异常以强制按需发生。这非常适合创建您自己的错误定义以及何时应将控制转移到捕获。</p>
<p><br></p>
<h3>更多建议</h3>
<h3>扔“我是邪恶的”</h3>
<p><code>throw</code>将 <strong>终止</strong> 进一步执行并在 <strong>捕获</strong> 错误时公开消息字符串。</p>
<div class="code"><pre class="code literal-block">try {
  throw "I'm Evil"
  console.log("You'll never reach to me", 123465)
} catch (e) {
  console.log(e); // I'm Evil
}
</pre></div>

<p>运行代码片段隐藏结果</p>
<p><strong>投掷</strong> 后的控制台将永远不会到达终止原因。</p>
<hr>
<h3>抛出新的错误（“我是邪恶的”）</h3>
<p><code>throw new Error</code>公开一个带有两个参数 <strong>name</strong> 和 <strong>message 的</strong> 错误事件。它还终止进一步执行</p>
<div class="code"><pre class="code literal-block">try {
  throw new Error("I'm Evil")
  console.log("You'll never reach to me", 123465)
} catch (e) {
  console.log(e.name, e.message); // Error I'm Evil
}
</pre></div>

<p>运行代码片段隐藏结果</p>
<h3>抛出错误（“我是邪恶的”）</h3>
<p>只是为了完整起见，这也有效，尽管从技术上讲这不是正确的方法 -</p>
<div class="code"><pre class="code literal-block">try {
  throw Error("I'm Evil")
  console.log("You'll never reach to me", 123465)
} catch (e) {
  console.log(e.name, e.message); // Error I'm Evil
}

console.log(typeof(new Error("hello"))) // object
console.log(typeof(Error)) // function
</pre></div>

<p>运行代码片段隐藏结果</p>
<p><br><br><a href="../what-is-the-difference-between-throw-new-error-and-throw-someobject/">查看原文</a></p>
    </div>
    <aside class="postpromonav"><nav><ul itemprop="keywords" class="tags">
<li><a class="tag p-category" href="../../categories/error-handling/" rel="tag">error-handling</a></li>
            <li><a class="tag p-category" href="../../categories/exception/" rel="tag">exception</a></li>
            <li><a class="tag p-category" href="../../categories/javascript/" rel="tag">javascript</a></li>
            <li><a class="tag p-category" href="../../categories/object/" rel="tag">object</a></li>
            <li><a class="tag p-category" href="../../categories/throw/" rel="tag">throw</a></li>
        </ul>
<ul class="pager hidden-print">
<li class="previous">
                <a href="../typescript-shi-fou-zhi-chi-cao-zuo-yuan-huan-you-ta-jiao-shi-yao/" rel="prev" title="Typescript 是否支持 ?. 操作员？（还有，它叫什么？）">Previous post</a>
            </li>
            <li class="next">
                <a href="../ru-he-xuan-zhuan-shu-ju-kuang/" rel="next" title="如何旋转数据框？">Next post</a>
            </li>
        </ul></nav></aside></article>
</div>
        <!--End of body content-->

        <footer id="footer">
            Contents © 2023         Go to StackOverflow Chinese Site  <a href="http://stackoverflow.ink">StackOverflow-ZH</a>  
            
        </footer>
</div>
</div>


            <script src="../../assets/js/all-nocdn.js"></script><!-- fancy dates --><script>
    moment.locale("en");
    fancydates(0, "YYYY-MM-DD HH:mm");
    </script><!-- end fancy dates --><script>
    baguetteBox.run('div#content', {
        ignoreClass: 'islink',
        captions: function(element) {
            return element.getElementsByTagName('img')[0].alt;
    }});
    </script><script src="../../assets/js/search.js"></script>
</body>
</html>
